version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      day-of-month: "1"
    commit-message:
      prefix: "chore"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "go"
