version: 2
updates:
  - package-ecosystem: "gomod"
    cooldown:
      default-days: 7
    directory: "/"
    groups:
      go-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
    pull-request-branch-name:
      separator: "/"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "go"
