/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`list_activity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListActivityError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_engagement_activity`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEngagementActivityError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}


/// Administrators only. Platform events — logins, lockouts, token lifecycle, MFA changes, role changes — with no engagement. Engagement-scoped rows are not included; use `GET /engagements/{engagementId}/activity` for those.  Newest first. Pagination is the standard cursor convention. Filter by actor, verb or object to narrow an incident review. 
pub async fn list_activity(configuration: &configuration::Configuration, limit: Option<i32>, cursor: Option<&str>, actor: Option<&str>, verb: Option<&str>, object_type: Option<&str>, object_id: Option<&str>) -> Result<models::ActivityPage, Error<ListActivityError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_limit = limit;
    let p_query_cursor = cursor;
    let p_query_actor = actor;
    let p_query_verb = verb;
    let p_query_object_type = object_type;
    let p_query_object_id = object_id;

    let uri_str = format!("{}/activity", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_actor {
        req_builder = req_builder.query(&[("actor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_verb {
        req_builder = req_builder.query(&[("verb", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_object_type {
        req_builder = req_builder.query(&[("objectType", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_object_id {
        req_builder = req_builder.query(&[("objectId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ActivityPage`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ActivityPage`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListActivityError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Members of the engagement, and platform administrators. The rows that name this engagement — comments, executions, membership changes once those exist — newest first.  A non-member is answered 404 rather than 403, so the existence of an engagement is not confirmed to someone outside it. 
pub async fn list_engagement_activity(configuration: &configuration::Configuration, engagement_id: &str, limit: Option<i32>, cursor: Option<&str>, actor: Option<&str>, verb: Option<&str>, object_type: Option<&str>, object_id: Option<&str>) -> Result<models::ActivityPage, Error<ListEngagementActivityError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_query_limit = limit;
    let p_query_cursor = cursor;
    let p_query_actor = actor;
    let p_query_verb = verb;
    let p_query_object_type = object_type;
    let p_query_object_id = object_id;

    let uri_str = format!("{}/engagements/{engagementId}/activity", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_actor {
        req_builder = req_builder.query(&[("actor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_verb {
        req_builder = req_builder.query(&[("verb", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_object_type {
        req_builder = req_builder.query(&[("objectType", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_object_id {
        req_builder = req_builder.query(&[("objectId", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ActivityPage`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ActivityPage`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListEngagementActivityError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

