/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`export_engagement`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExportEngagementError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`export_engagement_archive`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExportEngagementArchiveError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_analytics_burndown`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAnalyticsBurndownError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_analytics_compare`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAnalyticsCompareError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_analytics_coverage`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAnalyticsCoverageError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_analytics_distribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAnalyticsDistributionError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_analytics_mttd`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAnalyticsMttdError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_analytics_navigator_layer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAnalyticsNavigatorLayerError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}


/// Flat, tabular exports of the engagement workbook. One dataset per request; JSON and CSV share the same shape — one source, two encoders. The response is streamed, not buffered in memory.  CSV columns that start with =, +, -, @, tab or CR are escaped with a single-quote prefix to prevent formula injection.  Times are RFC 3339 UTC; durations are integer seconds. 
pub async fn export_engagement(configuration: &configuration::Configuration, engagement_id: &str, format: &str, dataset: &str) -> Result<String, Error<ExportEngagementError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_query_format = format;
    let p_query_dataset = dataset;

    let uri_str = format!("{}/engagements/{engagementId}/export", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("format", &p_query_format.to_string())]);
    req_builder = req_builder.query(&[("dataset", &p_query_dataset.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExportEngagementError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// One versioned, self-contained archive of an engagement: structure, scores, findings, comments, activity and evidence files. The response is a streamed ZIP (Content-Type: application/zip). Format is documented in docs/archive.md.  The archive carries a formatVersion integer at the top of manifest.json; a reader that does not recognise it must bail before parsing anything else.  Blind scoping: a blue caller in a blind engagement receives a partial archive without unrevealed steps, their executions, evidence, or activity. The manifest records blindFiltered: true.  Export only — there is no import endpoint in v1. 
pub async fn export_engagement_archive(configuration: &configuration::Configuration, engagement_id: &str) -> Result<reqwest::Response, Error<ExportEngagementArchiveError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;

    let uri_str = format!("{}/engagements/{engagementId}/archive", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<ExportEngagementArchiveError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Burndown from finding_status_history, not activity log — retention-safe. severity snapshot is point-in-time view of current finding counts by severity. 
pub async fn get_analytics_burndown(configuration: &configuration::Configuration, engagement_id: &str, interval: Option<models::BurndownInterval>) -> Result<models::AnalyticsBurndown, Error<GetAnalyticsBurndownError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_query_interval = interval;

    let uri_str = format!("{}/engagements/{engagementId}/analytics/burndown", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_interval {
        req_builder = req_builder.query(&[("interval", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AnalyticsBurndown`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AnalyticsBurndown`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAnalyticsBurndownError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Compare current engagement against baseline. Caller must hold report.read on both. Techniques matched on (technique_id, subtechnique_id) then template_id. No baseline_engagement_id column — any two readable engagements can be compared. 
pub async fn get_analytics_compare(configuration: &configuration::Configuration, engagement_id: &str, baseline: &str) -> Result<models::AnalyticsCompare, Error<GetAnalyticsCompareError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_query_baseline = baseline;

    let uri_str = format!("{}/engagements/{engagementId}/analytics/compare", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("baseline", &p_query_baseline.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AnalyticsCompare`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AnalyticsCompare`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAnalyticsCompareError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Both denominators — attempted (headline) matrix (pinned ATT&CK version) — are named fields. No bare percentage. Sub-techniques their own cells; parent technique counts covered only if step names it directly. 
pub async fn get_analytics_coverage(configuration: &configuration::Configuration, engagement_id: &str) -> Result<models::AnalyticsCoverage, Error<GetAnalyticsCoverageError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;

    let uri_str = format!("{}/engagements/{engagementId}/analytics/coverage", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AnalyticsCoverage`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AnalyticsCoverage`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAnalyticsCoverageError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// All four distributions in one payload. Every bucket carries unscored count; modifier counts are non-exclusive — one execution can carry several modifiers. 
pub async fn get_analytics_distribution(configuration: &configuration::Configuration, engagement_id: &str) -> Result<models::AnalyticsDistribution, Error<GetAnalyticsDistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;

    let uri_str = format!("{}/engagements/{engagementId}/analytics/distribution", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AnalyticsDistribution`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AnalyticsDistribution`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAnalyticsDistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// p50 / p90 / max over detected executions only. detectedCount undetectedCount mandatory fields — no consumer can render MTTD without denominator. 
pub async fn get_analytics_mttd(configuration: &configuration::Configuration, engagement_id: &str) -> Result<models::AnalyticsMttd, Error<GetAnalyticsMttdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;

    let uri_str = format!("{}/engagements/{engagementId}/analytics/mttd", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AnalyticsMttd`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AnalyticsMttd`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAnalyticsMttdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a Navigator layer document (JSON) keyed to the engagement's pinned ATT&CK version. Scores come from the detection-category ordinal; the colour ramp is documented in docs/analytics.md. The layer is downloadable — Content-Disposition: attachment with the engagement name in the filename. 
pub async fn get_analytics_navigator_layer(configuration: &configuration::Configuration, engagement_id: &str) -> Result<models::NavigatorLayer, Error<GetAnalyticsNavigatorLayerError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;

    let uri_str = format!("{}/engagements/{engagementId}/analytics/navigator-layer", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NavigatorLayer`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NavigatorLayer`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAnalyticsNavigatorLayerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

