/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`change_password`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChangePasswordError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`complete_oidc_sign_in`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompleteOidcSignInError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`complete_saml_sign_in`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompleteSamlSignInError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`confirm_totp`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfirmTotpError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_service_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateServiceTokenError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status409(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`disable_totp`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DisableTotpError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`enroll_totp`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EnrollTotpError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status409(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_auth_providers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAuthProvidersError {
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_current_user`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCurrentUserError {
    Status401(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_saml_metadata`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSamlMetadataError {
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`guest_register`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GuestRegisterError {
    Status400(models::Problem),
    Status409(models::Problem),
    Status429(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_service_tokens`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListServiceTokensError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListSessionsError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`login`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LoginError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status429(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`logout`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LogoutError {
    Status403(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`regenerate_recovery_codes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RegenerateRecoveryCodesError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status409(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`revoke_other_sessions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RevokeOtherSessionsError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`revoke_service_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RevokeServiceTokenError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`revoke_session`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RevokeSessionError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`start_oidc_sign_in`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StartOidcSignInError {
    Status400(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`start_saml_sign_in`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StartSamlSignInError {
    Status400(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`verify_recovery_code`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VerifyRecoveryCodeError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status429(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`verify_totp`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VerifyTotpError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status429(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}


/// Requires the current password, so that a borrowed browser cannot be used to take an account over.  On success the current session is rotated — a new token for the same session, in a new cookie — and every *other* session belonging to this user is revoked. Changing your password signs out the places you did not change it from. 
pub async fn change_password(configuration: &configuration::Configuration, change_password_request: models::ChangePasswordRequest, x_csrf_token: Option<&str>) -> Result<(), Error<ChangePasswordError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_change_password_request = change_password_request;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/auth/password", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_change_password_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ChangePasswordError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Where the identity provider sends the browser back. Register `<BLACKLIGHT_BASE_URL>/api/v1/auth/oidc/callback` as the redirect URI at the provider; it must match byte for byte.  On success this behaves exactly like `POST /auth/login` with `status: authenticated`: the session cookie and the `bl_csrf` cookie are set, and the browser is redirected to `return_to` — or to `/` when the sign-in named none. The pending-state cookie is cleared, which is what makes a `state` single-use.  The failures are worth telling apart, and none of them is a redirect:  - `401` — the callback does not belong to a sign-in this browser started   (no cookie, a `state` that does not match, an expired one), or the ID   token did not verify. Start again. - `403` — the provider vouched for somebody this deployment has no   account for and `BLACKLIGHT_OIDC_AUTO_PROVISION` is off, or the account   is disabled. The message says which and what to do about it; no account   is created. - `404` — no provider is configured.  A second factor still applies. An account that also has a local password and a confirmed authenticator is answered `mfa_required` in the same way a local sign-in is, and lands on the code entry page rather than signed in (M1-006, M1-008). 
pub async fn complete_oidc_sign_in(configuration: &configuration::Configuration, code: Option<&str>, state: Option<&str>, error: Option<&str>, error_description: Option<&str>) -> Result<(), Error<CompleteOidcSignInError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_code = code;
    let p_query_state = state;
    let p_query_error = error;
    let p_query_error_description = error_description;

    let uri_str = format!("{}/auth/oidc/callback", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_code {
        req_builder = req_builder.query(&[("code", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_state {
        req_builder = req_builder.query(&[("state", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_error {
        req_builder = req_builder.query(&[("error", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_error_description {
        req_builder = req_builder.query(&[("error_description", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CompleteOidcSignInError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// The assertion consumer service. The identity provider POSTs a form here from the browser; register `<BLACKLIGHT_BASE_URL>/api/v1/auth/saml/acs` as the ACS URL, and it must match byte for byte — it is checked against the assertion's `Recipient` and the response's `Destination`.  On success this behaves exactly like `POST /auth/login` with `status: authenticated`: the session cookie and the `bl_csrf` cookie are set, and the browser is redirected to the path the sign-in named, or to `/`.  Both SP-initiated and IdP-initiated sign-in are accepted. An SP-initiated one is additionally bound to the browser that started it — the sealed cookie names the request ID the assertion must answer, so an assertion delivered into somebody else's browser is refused. An IdP-initiated one has no request to answer and so cannot have that binding; set `BLACKLIGHT_SAML_ALLOW_IDP_INITIATED=false` on a deployment that does not need it.  The failures, and none of them is a redirect:  - `401` — the assertion was rejected. Unsigned, signed by a key that is   not the provider's, tampered with, outside its validity window,   addressed to somebody else, or one that has already been used. Which   of those it was is in the log and never in the response. - `403` — the assertion was good and this deployment will not sign that   person in: no account and `BLACKLIGHT_SAML_AUTO_PROVISION` is off, or   the account is disabled. - `404` — no provider is configured.  A second factor still applies, exactly as it does for OIDC (M1-006, M1-008). 
pub async fn complete_saml_sign_in(configuration: &configuration::Configuration, saml_response: &str, relay_state: Option<&str>) -> Result<(), Error<CompleteSamlSignInError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_form_saml_response = saml_response;
    let p_form_relay_state = relay_state;

    let uri_str = format!("{}/auth/saml/acs", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = std::collections::HashMap::new();
    multipart_form_params.insert("SAMLResponse", p_form_saml_response.to_string());
    if let Some(param_value) = p_form_relay_state {
        multipart_form_params.insert("RelayState", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<CompleteSamlSignInError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Proves the authenticator was actually set up. On success the enrolment becomes the second factor this account is asked for at sign-in, this session is marked as having satisfied MFA, and it is rotated onto a new token — satisfying a factor is a privilege change, and PLAN.md §4 wants the token to change whenever that is true.  It also mints ten **recovery codes** (M1-007) and returns them in the body. This is the only response in the API that ever carries them: there is no endpoint that reads them back, because the server keeps only their hashes. A client that does not put them in front of the person right now has lost them, and the only remedy is `POST /auth/mfa/recovery/regenerate`, which mints a different set.  A wrong code is a `400` naming the `code` field, not a `401`: the caller is signed in and this is a form to correct, not a session to re-establish. It is deliberately not throttled — the only secret being guessed is the caller's own, and getting it right grants them nothing they did not already have. 
pub async fn confirm_totp(configuration: &configuration::Configuration, totp_code_request: models::TotpCodeRequest, x_csrf_token: Option<&str>) -> Result<models::RecoveryCodes, Error<ConfirmTotpError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_totp_code_request = totp_code_request;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/auth/mfa/totp/confirm", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_totp_code_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RecoveryCodes`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RecoveryCodes`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfirmTotpError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Mints a token owned by you. **The response is the only time its secret exists outside your client** — it is stored as a hash and cannot be recovered, so a caller that does not save it has to create another one.  What the token may do is fenced twice, and the narrower fence wins on every request:  1. The scopes you give it here. 2. Your own permissions, read live on every request the token makes.    Being demoted narrows every token you hold, immediately, without    touching them; having your account disabled stops them entirely.  `engagementId` adds a third fence, and only ever subtracts: a token bound to an engagement reaches that engagement and nothing else — not another engagement, not the installation — whatever its scopes say. It cannot let a token into an engagement you are not a member of.  `expiresAt` is required and is capped at a year out. A credential with no expiry is one nobody remembers to revoke.  A service token cannot call this. Creating credentials takes a signed-in session, so that a leaked token cannot mint a longer-lived replacement for itself and outlive its own revocation — `403` with `code: \"forbidden\"` when one tries, whatever scopes it carries. 
pub async fn create_service_token(configuration: &configuration::Configuration, create_service_token_request: models::CreateServiceTokenRequest, x_csrf_token: Option<&str>) -> Result<models::CreatedServiceToken, Error<CreateServiceTokenError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_create_service_token_request = create_service_token_request;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/auth/tokens", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_service_token_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CreatedServiceToken`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CreatedServiceToken`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateServiceTokenError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Requires the current password, for the same reason changing a password does: a session left open on a shared machine must not be enough to take the second factor off an account.  The recovery codes go with it (M1-007). They stand in for the authenticator, so leaving them behind would mean a second factor that was removed is still presentable — and the next enrolment mints its own set, so keeping these could only ever mean two live sets.  Refused with `403` when a second factor is required of this person (M1-008) — by the platform policy or by their own `mfaEnforced` flag, which are the same answer here. Removing it would leave an account subject to a requirement it can no longer satisfy, which is a lockout rather than a choice. `mfa.required` on `GET /auth/me` says in advance whether this call will be refused. 
pub async fn disable_totp(configuration: &configuration::Configuration, disable_totp_request: models::DisableTotpRequest, x_csrf_token: Option<&str>) -> Result<(), Error<DisableTotpError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_disable_totp_request = disable_totp_request;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/auth/mfa/totp", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_disable_totp_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DisableTotpError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Mints a fresh shared secret and returns it three ways: as an `otpauth://` URI, as a QR code to point a camera at, and as the base32 string to type in when the camera will not focus.  The secret is **unconfirmed** until `POST /auth/mfa/totp/confirm` succeeds. An unconfirmed secret gates nothing — a browser closed between this call and that one leaves the account exactly as it was, which is what stops a half-finished enrolment locking somebody out.  Calling this again replaces an unconfirmed secret, so a re-scan works. It refuses with `409` when a *confirmed* authenticator already exists: replacing one is `DELETE /auth/mfa/totp` followed by this, and that needs the current password.  This is the only response that ever carries the secret. 
pub async fn enroll_totp(configuration: &configuration::Configuration, x_csrf_token: Option<&str>) -> Result<models::TotpEnrolment, Error<EnrollTotpError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/auth/mfa/totp/enroll", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TotpEnrolment`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TotpEnrolment`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<EnrollTotpError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Public, because it is what the login page reads *before* anybody has signed in — it is the list of buttons to draw.  `password` is whether local sign-in is offered, and `sso` is one entry per configured single sign-on provider, each with the URL to send the browser to.  A provider that is configured but cannot be reached is **absent** from `sso` (M1-009). That is deliberate and it is the point of this endpoint: a button that leads to a provider which is down is worse than no button, and an identity provider having a bad morning must never be the reason nobody can get in. It reappears on its own, with no restart, once the provider answers again.  It reveals that a deployment has single sign-on and which protocol, which is visible from the sign-in page of every such product and is not a secret. It reveals nothing about the client, the issuer or the mapping. 
pub async fn get_auth_providers(configuration: &configuration::Configuration, ) -> Result<models::AuthProviders, Error<GetAuthProvidersError>> {

    let uri_str = format!("{}/auth/providers", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AuthProviders`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AuthProviders`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetAuthProvidersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Everything the interface needs to decide what to show: who you are, what you may do to this installation, which engagements you are in and with which role, and whether this session has satisfied MFA.  It never returns anything about the session token. What is in the cookie stays in the cookie. 
pub async fn get_current_user(configuration: &configuration::Configuration, ) -> Result<models::CurrentUser, Error<GetCurrentUserError>> {

    let uri_str = format!("{}/auth/me", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CurrentUser`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CurrentUser`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetCurrentUserError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// The XML an identity provider administrator uploads, or points their console at, to register this deployment as a service provider (M1-010). It carries the entity ID, the assertion consumer service URL and the signing certificate.  It is public and it is meant to be: every field in it is something the identity provider is about to be told anyway, and half of them are already visible in the authentication request the browser carries. The **private** key never appears here — only the certificate, which is the public half.  `404` when this deployment has no SAML configured. 
pub async fn get_saml_metadata(configuration: &configuration::Configuration, ) -> Result<String, Error<GetSamlMetadataError>> {

    let uri_str = format!("{}/auth/saml/metadata", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetSamlMetadataError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Public. Creates a local user account with no platform role beyond member and no engagement memberships. Intended for share invite recipients who do not yet have an account.  Rate-limited like login to prevent account enumeration. 
pub async fn guest_register(configuration: &configuration::Configuration, guest_register_request: models::GuestRegisterRequest) -> Result<models::GuestRegisterResult, Error<GuestRegisterError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_guest_register_request = guest_register_request;

    let uri_str = format!("{}/auth/guest-register", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_guest_register_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GuestRegisterResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GuestRegisterResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GuestRegisterError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Your tokens, newest first, including the expired and revoked ones — you cannot decide whether to rotate something you cannot see the history of.  No secret is here, and none could be: the server stores a hash, so it could not produce a token's value if asked. `prefix` is what identifies a row to a human, and it is the same value that appears in the middle of the token itself.  Yours and nobody else's. There is no parameter that names another account, and an administrator calling this sees their own tokens like everybody else. An administrator who needs to see somebody else's has `GET /users/{userId}/tokens`, which is a different permission and a different endpoint — this one never widens. 
pub async fn list_service_tokens(configuration: &configuration::Configuration, ) -> Result<models::ServiceTokens, Error<ListServiceTokensError>> {

    let uri_str = format!("{}/auth/tokens", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ServiceTokens`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ServiceTokens`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListServiceTokensError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Your own live sessions, newest first, and nobody else's — there is no parameter that names another account. An administrator wanting somebody else's reaches for `POST /users/{userId}/sessions/revoke`, which ends them rather than reading them.  **Live** means what the authentication middleware means by it: not revoked, not past its absolute expiry, and not idle for longer than the idle timeout. The same function decides both, so this list cannot disagree with what would actually be accepted on the next request — a row here is a browser that could act right now, which is what makes revoking one worth doing.  `current` marks the session this request arrived on. It is the one row a client should not offer an ordinary \"revoke\" for: ending it is signing out, and `POST /auth/logout` is where that lives, with the cookie clearing that goes with it.  No token and no hash of one. What is in the cookie stays in the cookie. 
pub async fn list_sessions(configuration: &configuration::Configuration, ) -> Result<models::Sessions, Error<ListSessionsError>> {

    let uri_str = format!("{}/auth/sessions", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Sessions`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Sessions`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListSessionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Public, because the caller has no session yet — that is what this endpoint issues.  Every way of failing produces the *same* 401 with the same body: a wrong password, an address nobody holds, and a disabled account are indistinguishable, so that this endpoint cannot be used to find out who has an account here. The server spends the same work on each, too.  A 200 does not always mean a session. When a second factor is required and the caller has one, `status` is `mfa_required`, no *session* cookie is set, and they must post a code to `POST /auth/mfa/totp/verify` — or a recovery code to `POST /auth/mfa/recovery/verify` (M1-007) — before anything is signed in (M1-006).  When one is required and they have **none**, `status` is `mfa_enrolment_required`: a session cookie is set and it may do exactly one thing, which is enrol (M1-008). Read `status` rather than assuming.  Attempts are throttled per account and per client address (M1-004). Once either limit trips, every attempt is a 429 with a `Retry-After` — the right password included, because a lockout that the right password ends is not a lockout. The 429 is identical for an account that exists and one that does not. 
pub async fn login(configuration: &configuration::Configuration, login_request: models::LoginRequest) -> Result<models::LoginResult, Error<LoginError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_login_request = login_request;

    let uri_str = format!("{}/auth/login", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_login_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LoginResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LoginResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<LoginError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Revokes the session server-side and clears the cookie. A replay of the old cookie afterwards is a 401 — the session is ended in the database, not merely forgotten by the browser.  A request that carries no usable session is a 204 as well: the caller wanted to be signed out, and they are. 
pub async fn logout(configuration: &configuration::Configuration, x_csrf_token: Option<&str>) -> Result<(), Error<LogoutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/auth/logout", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<LogoutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Mints ten new codes and **invalidates every previous one**, including the codes that were never used. Somebody regenerating because a printout went missing is telling us the missing printout must stop working.  It asks for two things. The current password, so that a session left open on a shared machine cannot mint credentials that walk past a second factor. And a session that has already satisfied MFA — `403` otherwise. Deliberately *not* a fresh code from the authenticator: signing in with a recovery code produces a satisfied session, so this is reachable by the person whose phone is gone, which is the case recovery codes exist for.  `409` when no authenticator is enrolled: codes stand in for one, and there has to be one to stand in for.  Like the enrolment response, this is the only time the new codes exist outside the client. 
pub async fn regenerate_recovery_codes(configuration: &configuration::Configuration, regenerate_recovery_codes_request: models::RegenerateRecoveryCodesRequest, x_csrf_token: Option<&str>) -> Result<models::RecoveryCodes, Error<RegenerateRecoveryCodesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_regenerate_recovery_codes_request = regenerate_recovery_codes_request;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/auth/mfa/recovery/regenerate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_regenerate_recovery_codes_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RecoveryCodes`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RecoveryCodes`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RegenerateRecoveryCodesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Ends every session you hold except the one making the request, and reports how many. The browser doing the asking keeps working, which is what separates this from signing out.  It is the one control that is useful without reading the list first: the person who has just remembered a laptop in a hotel does not need to identify which row it is.  Idempotent, and `revoked: 0` is a normal answer for somebody signed in only here. Service tokens are not sessions and are untouched — those are `DELETE /auth/tokens/{tokenId}`. 
pub async fn revoke_other_sessions(configuration: &configuration::Configuration, x_csrf_token: Option<&str>) -> Result<models::RevokedSessions, Error<RevokeOtherSessionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/auth/sessions/revoke-others", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RevokedSessions`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RevokedSessions`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RevokeOtherSessionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Takes effect on the token's next request: there is no cached copy of it anywhere, so there is no window during which it still works.  Idempotent — revoking a token that has already been revoked answers the same way, and keeps the original revocation time, because the first revocation is when access actually stopped.  A token belonging to somebody else answers `404`, exactly as an identifier that names nothing does. The two are indistinguishable on purpose: an endpoint that answered `403` for real identifiers and `404` for invented ones would be a way to find out which are real. An administrator revoking somebody else's uses `DELETE /users/{userId}/tokens/{tokenId}`, which names the account.  As with creation, a service token cannot call this. 
pub async fn revoke_service_token(configuration: &configuration::Configuration, token_id: &str, x_csrf_token: Option<&str>) -> Result<(), Error<RevokeServiceTokenError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_token_id = token_id;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/auth/tokens/{tokenId}", configuration.base_path, tokenId=crate::apis::urlencode(p_path_token_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RevokeServiceTokenError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Takes effect at that browser's next request: the row is revoked, and every request resolves its session from the row rather than from anything cached.  A session belonging to somebody else answers `404`, exactly as an identifier that names nothing does, and for the same reason `DELETE /auth/tokens/{tokenId}` does: an endpoint that answered `403` for real identifiers and `404` for invented ones would be a way to find out which are real.  Revoking the session making the request is allowed and is a way to sign out — but it leaves this browser holding a cookie nothing accepts and nothing told it to drop, so `POST /auth/logout` is the operation for that. Clients should offer it for the other rows. 
pub async fn revoke_session(configuration: &configuration::Configuration, session_id: &str, x_csrf_token: Option<&str>) -> Result<(), Error<RevokeSessionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_session_id = session_id;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/auth/sessions/{sessionId}", configuration.base_path, sessionId=crate::apis::urlencode(p_path_session_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RevokeSessionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Redirects the browser to the identity provider's authorization endpoint with PKCE, `state` and `nonce`, and sets a short-lived, sealed cookie holding all three (M1-009). It is a navigation rather than a fetch: send the browser here, do not call it with `fetch`.  `return_to` is where to land afterwards and must be a path within this application — a relative path beginning with a single `/`. Anything else is a `400`: an endpoint that redirects wherever a query parameter says is an open redirect, and an open redirect on the login path is a credible phishing page on your own domain.  `404` when no provider is configured, or when the configured one cannot be reached. Local sign-in is unaffected either way. 
pub async fn start_oidc_sign_in(configuration: &configuration::Configuration, return_to: Option<&str>) -> Result<(), Error<StartOidcSignInError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_return_to = return_to;

    let uri_str = format!("{}/auth/oidc/start", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_return_to {
        req_builder = req_builder.query(&[("return_to", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<StartOidcSignInError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Redirects the browser to the identity provider's single sign-on service with a signed `AuthnRequest` (HTTP-Redirect binding), and sets a short-lived, sealed cookie holding that request's ID and where to land afterwards. It is a navigation rather than a fetch: send the browser here, do not call it with `fetch`.  `return_to` is where to land afterwards and must be a path within this application, exactly as it is for `GET /auth/oidc/start`, and for the same reason: an endpoint that redirects wherever a query parameter says is an open redirect on the login path.  `404` when no provider is configured, or when the configured one's metadata could not be read. Local sign-in is unaffected either way. 
pub async fn start_saml_sign_in(configuration: &configuration::Configuration, return_to: Option<&str>) -> Result<(), Error<StartSamlSignInError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_return_to = return_to;

    let uri_str = format!("{}/auth/saml/start", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_return_to {
        req_builder = req_builder.query(&[("return_to", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<StartSamlSignInError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// The other way out of `mfa_required`, for the person whose phone is in a river (M1-007). It takes the same short-lived `bl_mfa` cookie as `POST /auth/mfa/totp/verify` and one of the codes issued when the authenticator was enrolled.  A code works exactly once. On success it is marked used, the pending state is spent, and a session is issued with MFA **satisfied** — this is a full sign-in and not a diminished one, because someone holding a printed code has presented a second factor. `GET /auth/me` then reports `mfa.recoveryCodesRemaining` one lower; below three, warn them.  Every way of failing is the same `401` as the TOTP endpoint's: a code that is not theirs, one already used, one that is not a code at all, an expired pending state and no pending state at all. Attempts are throttled per account and per client address alongside password and TOTP attempts (M1-004). 
pub async fn verify_recovery_code(configuration: &configuration::Configuration, recovery_code_request: models::RecoveryCodeRequest) -> Result<models::LoginResult, Error<VerifyRecoveryCodeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_recovery_code_request = recovery_code_request;

    let uri_str = format!("{}/auth/mfa/recovery/verify", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_recovery_code_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LoginResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LoginResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<VerifyRecoveryCodeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// The second half of a sign-in that answered `mfa_required`. It carries no session — that is the point: the credential is the short-lived `bl_mfa` cookie set by `POST /auth/login`, which authorizes nothing except this endpoint and expires in minutes.  On success the pending state is spent, a session is issued with MFA satisfied, and the `bl_mfa` cookie is cleared. One correct code buys exactly one session.  Every way of failing is the same `401`: a wrong code, a code already used, an expired pending state, and no pending state at all. Attempts are throttled per account and per client address alongside password attempts (M1-004), and the `429` is identical whichever limit closed. 
pub async fn verify_totp(configuration: &configuration::Configuration, totp_code_request: models::TotpCodeRequest) -> Result<models::LoginResult, Error<VerifyTotpError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_totp_code_request = totp_code_request;

    let uri_str = format!("{}/auth/mfa/totp/verify", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_totp_code_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::LoginResult`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::LoginResult`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<VerifyTotpError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

