/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};
use tokio::fs::File as TokioFile;
use tokio_util::codec::{BytesCodec, FramedRead};


/// struct for typed errors of method [`delete_evidence`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteEvidenceError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_evidence`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEvidenceError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_evidence_content`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEvidenceContentError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_evidence_by_execution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEvidenceByExecutionError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`upload_evidence`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UploadEvidenceError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status409(models::Problem),
    Status413(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}


/// Uploader, lead or platform administrator. Decrements the blob refcount; if it reaches zero the blob file is removed from disk.  Closed engagements still allow delete (cleanup), unlike uploads. Activity: `evidence.deleted`. 
pub async fn delete_evidence(configuration: &configuration::Configuration, evidence_id: &str, x_csrf_token: Option<&str>) -> Result<(), Error<DeleteEvidenceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_evidence_id = evidence_id;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/evidence/{evidenceId}", configuration.base_path, evidenceId=crate::apis::urlencode(p_path_evidence_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteEvidenceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Any engagement member who can read the owning execution. In blind mode, evidence on an unrevealed step is 404-concealed. 
pub async fn get_evidence(configuration: &configuration::Configuration, evidence_id: &str) -> Result<models::Evidence, Error<GetEvidenceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_evidence_id = evidence_id;

    let uri_str = format!("{}/evidence/{evidenceId}", configuration.base_path, evidenceId=crate::apis::urlencode(p_path_evidence_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Evidence`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Evidence`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetEvidenceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Any engagement member who can read the owning execution. Content-Type is the stored MIME from upload (allowlisted). Content-Disposition: attachment with filename. X-Content-Type-Options: nosniff. 
pub async fn get_evidence_content(configuration: &configuration::Configuration, evidence_id: &str) -> Result<reqwest::Response, Error<GetEvidenceContentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_evidence_id = evidence_id;

    let uri_str = format!("{}/evidence/{evidenceId}/content", configuration.base_path, evidenceId=crate::apis::urlencode(p_path_evidence_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text().await?;
        let entity: Option<GetEvidenceContentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Any engagement member who can read the execution. Evidence on unrevealed steps in blind mode is concealed (same rule as execution.read). Newest first. 
pub async fn list_evidence_by_execution(configuration: &configuration::Configuration, execution_id: &str) -> Result<Vec<models::Evidence>, Error<ListEvidenceByExecutionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_execution_id = execution_id;

    let uri_str = format!("{}/executions/{executionId}/evidence", configuration.base_path, executionId=crate::apis::urlencode(p_path_execution_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Evidence&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Evidence&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListEvidenceByExecutionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lead, red, blue and platform administrators. Observer cannot upload. Domain enforces side: red seat → side=red only; blue → blue; lead → either; admin without seat may write either for support.  File is streamed to a temp file and content-addressed by SHA-256: identical bytes uploaded twice produce one blob on disk with ref_count=2. MIME is validated against the configured allowlist. Default limits: 25 MiB per file, 2 GiB per engagement.  Closed engagements return 409. Activity: `evidence.uploaded`. 
pub async fn upload_evidence(configuration: &configuration::Configuration, execution_id: &str, file: std::path::PathBuf, side: models::EvidenceSide, x_csrf_token: Option<&str>, caption: Option<&str>) -> Result<models::Evidence, Error<UploadEvidenceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_execution_id = execution_id;
    let p_form_file = file;
    let p_form_side = side;
    let p_header_x_csrf_token = x_csrf_token;
    let p_form_caption = caption;

    let uri_str = format!("{}/executions/{executionId}/evidence", configuration.base_path, executionId=crate::apis::urlencode(p_path_execution_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    let mut multipart_form = reqwest::multipart::Form::new();
    let file = TokioFile::open(&p_form_file).await?;
    let stream = FramedRead::new(file, BytesCodec::new());
    let file_name = p_form_file.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default();
    let file_part = reqwest::multipart::Part::stream(reqwest::Body::wrap_stream(stream)).file_name(file_name);
    multipart_form = multipart_form.part("file", file_part);
    if let Some(param_value) = p_form_caption {
        multipart_form = multipart_form.text("caption", param_value.to_string());
    }
    multipart_form = multipart_form.text("side", p_form_side.to_string());
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Evidence`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Evidence`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UploadEvidenceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

