/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};
use tokio::fs::File as TokioFile;
use tokio_util::codec::{BytesCodec, FramedRead};


/// struct for typed errors of method [`create_comment`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateCommentError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status409(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_execution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetExecutionError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_comments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCommentsError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_engagement_executions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEngagementExecutionsError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_evidence_by_execution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEvidenceByExecutionError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_blue_detection`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchBlueDetectionError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status409(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_red_execution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchRedExecutionError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status409(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`upload_evidence`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UploadEvidenceError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status409(models::Problem),
    Status413(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}


/// Write one comment. The author is the authenticated caller. Observers hold `comment.write` — it is their only write. Cannot comment on an unrevealed execution in blind mode. Closed engagements still accept comments. 
pub async fn create_comment(configuration: &configuration::Configuration, engagement_id: &str, execution_id: &str, create_comment: models::CreateComment, x_csrf_token: Option<&str>) -> Result<models::Comment, Error<CreateCommentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_path_execution_id = execution_id;
    let p_body_create_comment = create_comment;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/engagements/{engagementId}/executions/{executionId}/comments", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id), executionId=crate::apis::urlencode(p_path_execution_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_create_comment);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Comment`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Comment`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateCommentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Members and platform administrators. In a blind engagement, an execution belonging to an unrevealed step is 404-concealed for blue. 
pub async fn get_execution(configuration: &configuration::Configuration, engagement_id: &str, execution_id: &str) -> Result<models::Execution, Error<GetExecutionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_path_execution_id = execution_id;

    let uri_str = format!("{}/engagements/{engagementId}/executions/{executionId}", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id), executionId=crate::apis::urlencode(p_path_execution_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Execution`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Execution`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetExecutionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns every comment on this execution, oldest first. Members of the engagement may read comments. In blind mode, comments on an unrevealed step are 404-concealed. 
pub async fn list_comments(configuration: &configuration::Configuration, engagement_id: &str, execution_id: &str) -> Result<Vec<models::Comment>, Error<ListCommentsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_path_execution_id = execution_id;

    let uri_str = format!("{}/engagements/{engagementId}/executions/{executionId}/comments", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id), executionId=crate::apis::urlencode(p_path_execution_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Comment&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Comment&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListCommentsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Members and platform administrators. Filters by scenario and/or status. In a blind engagement, blue members only see executions for revealed steps. 
pub async fn list_engagement_executions(configuration: &configuration::Configuration, engagement_id: &str, scenario_id: Option<&str>, status: Option<models::ExecutionStatus>) -> Result<models::ExecutionList, Error<ListEngagementExecutionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_query_scenario_id = scenario_id;
    let p_query_status = status;

    let uri_str = format!("{}/engagements/{engagementId}/executions", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_scenario_id {
        req_builder = req_builder.query(&[("scenarioId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ExecutionList`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ExecutionList`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListEngagementExecutionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Any engagement member who can read the execution. Evidence on unrevealed steps in blind mode is concealed (same rule as execution.read). Newest first. 
pub async fn list_evidence_by_execution(configuration: &configuration::Configuration, execution_id: &str) -> Result<Vec<models::Evidence>, Error<ListEvidenceByExecutionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_execution_id = execution_id;

    let uri_str = format!("{}/executions/{executionId}/evidence", configuration.base_path, executionId=crate::apis::urlencode(p_path_execution_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Evidence&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Evidence&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListEvidenceByExecutionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lead, blue and platform administrators. The PATCH body only accepts detection fields — category, modifiers, protection, timestamps, source/rule ref, severity and notes — so a red client cannot send fields it does not own. Optimistic locking: `version` is required and must match; mismatch → 409.  `detected_at` before `started_at` (when both are set) → 400. Unreported fields are left unchanged. Unknown modifier or category → 400.  A closed engagement returns 409. `scored_by` and `scored_at` are set when detection category or protection changes (on any successful patch).  Activity: `execution.blue_updated`. 
pub async fn patch_blue_detection(configuration: &configuration::Configuration, engagement_id: &str, execution_id: &str, blue_detection_patch: models::BlueDetectionPatch, x_csrf_token: Option<&str>) -> Result<models::Execution, Error<PatchBlueDetectionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_path_execution_id = execution_id;
    let p_body_blue_detection_patch = blue_detection_patch;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/engagements/{engagementId}/executions/{executionId}/detection", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id), executionId=crate::apis::urlencode(p_path_execution_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_blue_detection_patch);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Execution`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Execution`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PatchBlueDetectionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lead, red and platform administrators. The PATCH body only accepts red fields — status, timestamps, command, hosts, notes — so a blue client cannot send fields it does not own. Optimistic locking: `version` is required and must match; mismatch → 409.  Status transitions: `pending` → `running`|`skipped`|`blocked`; `running` → `complete`|`blocked`|`skipped`. Terminal states (complete/blocked/skipped) accept note/host/command edits without a status change. Illegal jumps → 409.  Auto-reveal: when the status becomes `running` or `complete` and the engagement is blind with `auto_reveal_on_start` enabled and the step is unrevealed, the step is revealed in the same transaction.  A closed engagement returns 409. The first non-pending transition sets `executed_by` to the caller's id if still empty. 
pub async fn patch_red_execution(configuration: &configuration::Configuration, engagement_id: &str, execution_id: &str, red_execution_patch: models::RedExecutionPatch, x_csrf_token: Option<&str>) -> Result<models::Execution, Error<PatchRedExecutionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_path_execution_id = execution_id;
    let p_body_red_execution_patch = red_execution_patch;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/engagements/{engagementId}/executions/{executionId}/execution", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id), executionId=crate::apis::urlencode(p_path_execution_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_red_execution_patch);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Execution`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Execution`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PatchRedExecutionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lead, red, blue and platform administrators. Observer cannot upload. Domain enforces side: red seat → side=red only; blue → blue; lead → either; admin without seat may write either for support.  File is streamed to a temp file and content-addressed by SHA-256: identical bytes uploaded twice produce one blob on disk with ref_count=2. MIME is validated against the configured allowlist. Default limits: 25 MiB per file, 2 GiB per engagement.  Closed engagements return 409. Activity: `evidence.uploaded`. 
pub async fn upload_evidence(configuration: &configuration::Configuration, execution_id: &str, file: std::path::PathBuf, side: models::EvidenceSide, x_csrf_token: Option<&str>, caption: Option<&str>) -> Result<models::Evidence, Error<UploadEvidenceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_execution_id = execution_id;
    let p_form_file = file;
    let p_form_side = side;
    let p_header_x_csrf_token = x_csrf_token;
    let p_form_caption = caption;

    let uri_str = format!("{}/executions/{executionId}/evidence", configuration.base_path, executionId=crate::apis::urlencode(p_path_execution_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    let mut multipart_form = reqwest::multipart::Form::new();
    let file = TokioFile::open(&p_form_file).await?;
    let stream = FramedRead::new(file, BytesCodec::new());
    let file_name = p_form_file.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default();
    let file_part = reqwest::multipart::Part::stream(reqwest::Body::wrap_stream(stream)).file_name(file_name);
    multipart_form = multipart_form.part("file", file_part);
    if let Some(param_value) = p_form_caption {
        multipart_form = multipart_form.text("caption", param_value.to_string());
    }
    multipart_form = multipart_form.text("side", p_form_side.to_string());
    req_builder = req_builder.multipart(multipart_form);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Evidence`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Evidence`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UploadEvidenceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

