/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_finding`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateFindingError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status409(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_finding`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteFindingError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_finding`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetFindingError {
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_findings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListFindingsError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_finding`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchFindingError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status409(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`set_finding_steps`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SetFindingStepsError {
    Status400(models::Problem),
    Status401(models::Problem),
    Status403(models::Problem),
    Status404(models::Problem),
    Status500(models::Problem),
    UnknownValue(serde_json::Value),
}


/// Lead, red or blue raise a finding. Observers cannot create findings. Closed engagements return 409; updating status of existing findings to resolved is still permitted on closed engagements. Activity: `finding.created`. 
pub async fn create_finding(configuration: &configuration::Configuration, engagement_id: &str, new_finding: models::NewFinding, x_csrf_token: Option<&str>) -> Result<models::Finding, Error<CreateFindingError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_body_new_finding = new_finding;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/engagements/{engagementId}/findings", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_new_finding);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Finding`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Finding`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateFindingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lead or platform administrator. Deleting a finding also removes its finding_step join rows. Closed engagements are permitted. Activity: `finding.deleted`. 
pub async fn delete_finding(configuration: &configuration::Configuration, finding_id: &str, x_csrf_token: Option<&str>) -> Result<(), Error<DeleteFindingError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_finding_id = finding_id;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/findings/{findingId}", configuration.base_path, findingId=crate::apis::urlencode(p_path_finding_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteFindingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Any engagement member may read. Returns the finding with its linked step ids. 
pub async fn get_finding(configuration: &configuration::Configuration, finding_id: &str) -> Result<models::Finding, Error<GetFindingError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_finding_id = finding_id;

    let uri_str = format!("{}/findings/{findingId}", configuration.base_path, findingId=crate::apis::urlencode(p_path_finding_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Finding`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Finding`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetFindingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns every finding in this engagement, newest first. Any engagement member may read findings. Filters: status, severity, owner. 
pub async fn list_findings(configuration: &configuration::Configuration, engagement_id: &str, status: Option<models::FindingStatus>, severity: Option<models::FindingSeverity>, owner: Option<&str>) -> Result<Vec<models::Finding>, Error<ListFindingsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_engagement_id = engagement_id;
    let p_query_status = status;
    let p_query_severity = severity;
    let p_query_owner = owner;

    let uri_str = format!("{}/engagements/{engagementId}/findings", configuration.base_path, engagementId=crate::apis::urlencode(p_path_engagement_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_severity {
        req_builder = req_builder.query(&[("severity", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_owner {
        req_builder = req_builder.query(&[("owner", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Finding&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Finding&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListFindingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lead, red or blue may update a finding. Any field not sent stays unchanged. Closed engagements may still update the status field (e.g. to resolved); other fields on a closed engagement return 409. Activity: `finding.updated`. 
pub async fn patch_finding(configuration: &configuration::Configuration, finding_id: &str, patch_finding: models::PatchFinding, x_csrf_token: Option<&str>) -> Result<models::Finding, Error<PatchFindingError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_finding_id = finding_id;
    let p_body_patch_finding = patch_finding;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/findings/{findingId}", configuration.base_path, findingId=crate::apis::urlencode(p_path_finding_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_patch_finding);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Finding`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Finding`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PatchFindingError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Lead, red or blue may set the steps linked to this finding. The payload is the complete set of step ids; any step not listed is unlinked. All step ids must belong to the same engagement as the finding. Activity: `finding.steps_changed`. 
pub async fn set_finding_steps(configuration: &configuration::Configuration, finding_id: &str, finding_step_ids: models::FindingStepIds, x_csrf_token: Option<&str>) -> Result<(), Error<SetFindingStepsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_finding_id = finding_id;
    let p_body_finding_step_ids = finding_step_ids;
    let p_header_x_csrf_token = x_csrf_token;

    let uri_str = format!("{}/findings/{findingId}/steps", configuration.base_path, findingId=crate::apis::urlencode(p_path_finding_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(param_value) = p_header_x_csrf_token {
        req_builder = req_builder.header("X-CSRF-Token", param_value.to_string());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_finding_step_ids);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<SetFindingStepsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

