/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsMttd {
    #[serde(rename = "p50", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub p50: Option<Option<i32>>,
    #[serde(rename = "p90", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub p90: Option<Option<i32>>,
    #[serde(rename = "max", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max: Option<Option<i32>>,
    #[serde(rename = "detectedCount")]
    pub detected_count: i32,
    #[serde(rename = "undetectedCount")]
    pub undetected_count: i32,
    #[serde(rename = "unscoredCount")]
    pub unscored_count: i32,
    #[serde(rename = "unmeasurableCount")]
    pub unmeasurable_count: i32,
    #[serde(rename = "attemptedCount")]
    pub attempted_count: i32,
    #[serde(rename = "blindFiltered")]
    pub blind_filtered: bool,
}

impl AnalyticsMttd {
    pub fn new(detected_count: i32, undetected_count: i32, unscored_count: i32, unmeasurable_count: i32, attempted_count: i32, blind_filtered: bool) -> AnalyticsMttd {
        AnalyticsMttd {
            p50: None,
            p90: None,
            max: None,
            detected_count,
            undetected_count,
            unscored_count,
            unmeasurable_count,
            attempted_count,
            blind_filtered,
        }
    }
}

