/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BurndownInterval : Bucket granularity for the burndown chart.
/// Bucket granularity for the burndown chart.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BurndownInterval {
    #[serde(rename = "daily")]
    Daily,
    #[serde(rename = "weekly")]
    Weekly,

}

impl std::fmt::Display for BurndownInterval {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Daily => write!(f, "daily"),
            Self::Weekly => write!(f, "weekly"),
        }
    }
}

impl Default for BurndownInterval {
    fn default() -> BurndownInterval {
        Self::Daily
    }
}

