/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Comment {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "executionId")]
    pub execution_id: uuid::Uuid,
    /// User id of the comment's author.
    #[serde(rename = "authorId")]
    pub author_id: String,
    /// Markdown or plain text. 16 KiB limit.
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Null when never edited; set on first edit and updated thereafter.
    #[serde(rename = "editedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub edited_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl Comment {
    pub fn new(id: uuid::Uuid, execution_id: uuid::Uuid, author_id: String, body: String, created_at: chrono::DateTime<chrono::FixedOffset>) -> Comment {
        Comment {
            id,
            execution_id,
            author_id,
            body,
            created_at,
            edited_at: None,
        }
    }
}

