/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompareRow {
    #[serde(rename = "techniqueId")]
    pub technique_id: String,
    #[serde(rename = "subtechniqueId")]
    pub subtechnique_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "baselineCategory")]
    pub baseline_category: String,
    #[serde(rename = "baselineCategoryOrdinal", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub baseline_category_ordinal: Option<Option<i32>>,
    #[serde(rename = "baselineProtection")]
    pub baseline_protection: String,
    #[serde(rename = "currentCategory")]
    pub current_category: String,
    #[serde(rename = "currentCategoryOrdinal", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_category_ordinal: Option<Option<i32>>,
    #[serde(rename = "currentProtection")]
    pub current_protection: String,
    #[serde(rename = "ordinalDelta", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ordinal_delta: Option<Option<i32>>,
    #[serde(rename = "classification")]
    pub classification: String,
}

impl CompareRow {
    pub fn new(technique_id: String, subtechnique_id: String, name: String, baseline_category: String, baseline_protection: String, current_category: String, current_protection: String, classification: String) -> CompareRow {
        CompareRow {
            technique_id,
            subtechnique_id,
            name,
            baseline_category,
            baseline_category_ordinal: None,
            baseline_protection,
            current_category,
            current_category_ordinal: None,
            current_protection,
            ordinal_delta: None,
            classification,
        }
    }
}

