/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentSourceDetail {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "kind")]
    pub kind: models::ContentSourceKind,
    #[serde(rename = "name")]
    pub name: String,
    /// Default HTTPS archive / bundle base URL. Empty for custom.
    #[serde(rename = "url")]
    pub url: String,
    /// Adapter-specific ref pattern or branch/tag hint. Empty when unused.
    #[serde(rename = "ref")]
    pub r#ref: String,
    /// Soft switch. Disabled sources stay on disk; browse/search/pickers omit their objects and new references are refused. 
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "status")]
    pub status: models::ContentSourceStatus,
    /// When this source last finished a successful sync. Absent if never.
    #[serde(rename = "lastSyncedAt", skip_serializing_if = "Option::is_none")]
    pub last_synced_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Bookkeeping count of objects currently held for this source.
    #[serde(rename = "itemCount")]
    pub item_count: i64,
    /// Last error message from a failed job. Empty when none.
    #[serde(rename = "error")]
    pub error: String,
    /// SPDX license identifier.
    #[serde(rename = "licenseSpdx")]
    pub license_spdx: String,
    #[serde(rename = "licenseName")]
    pub license_name: String,
    #[serde(rename = "licenseUrl")]
    pub license_url: String,
    /// Attribution text shown in UI detail and export headers.
    #[serde(rename = "attribution")]
    pub attribution: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    /// Most recent job for this source, when any exists.
    #[serde(rename = "lastJob", skip_serializing_if = "Option::is_none")]
    pub last_job: Option<models::ContentSyncJobSummary>,
}

impl ContentSourceDetail {
    pub fn new(id: uuid::Uuid, kind: models::ContentSourceKind, name: String, url: String, r#ref: String, enabled: bool, status: models::ContentSourceStatus, item_count: i64, error: String, license_spdx: String, license_name: String, license_url: String, attribution: String, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> ContentSourceDetail {
        ContentSourceDetail {
            id,
            kind,
            name,
            url,
            r#ref,
            enabled,
            status,
            last_synced_at: None,
            item_count,
            error,
            license_spdx,
            license_name,
            license_url,
            attribution,
            created_at,
            updated_at,
            last_job: None,
        }
    }
}

