/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentImportReport : Result of a synchronous custom/v1 import or dry-run. Async jobs surface the same counts in the job message and activity delta. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentImportReport {
    #[serde(rename = "dryRun")]
    pub dry_run: bool,
    /// Resolved format after auto-detection.
    #[serde(rename = "format")]
    pub format: String,
    #[serde(rename = "proceduresCreated")]
    pub procedures_created: i32,
    #[serde(rename = "proceduresUpdated")]
    pub procedures_updated: i32,
    #[serde(rename = "notesCreated")]
    pub notes_created: i32,
    #[serde(rename = "notesUpdated")]
    pub notes_updated: i32,
    #[serde(rename = "detectionsCreated")]
    pub detections_created: i32,
    #[serde(rename = "detectionsUpdated")]
    pub detections_updated: i32,
    #[serde(rename = "warnings")]
    pub warnings: Vec<models::ContentImportIssue>,
    #[serde(rename = "errors")]
    pub errors: Vec<models::ContentImportIssue>,
}

impl ContentImportReport {
    /// Result of a synchronous custom/v1 import or dry-run. Async jobs surface the same counts in the job message and activity delta. 
    pub fn new(dry_run: bool, format: String, procedures_created: i32, procedures_updated: i32, notes_created: i32, notes_updated: i32, detections_created: i32, detections_updated: i32, warnings: Vec<models::ContentImportIssue>, errors: Vec<models::ContentImportIssue>) -> ContentImportReport {
        ContentImportReport {
            dry_run,
            format,
            procedures_created,
            procedures_updated,
            notes_created,
            notes_updated,
            detections_created,
            detections_updated,
            warnings,
            errors,
        }
    }
}

