/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentSyncJobKind : What a content sync job is doing.
/// What a content sync job is doing.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentSyncJobKind {
    #[serde(rename = "sync")]
    Sync,
    #[serde(rename = "reprocess")]
    Reprocess,
    #[serde(rename = "bundle_import")]
    BundleImport,
    #[serde(rename = "v1_import")]
    V1Import,

}

impl std::fmt::Display for ContentSyncJobKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sync => write!(f, "sync"),
            Self::Reprocess => write!(f, "reprocess"),
            Self::BundleImport => write!(f, "bundle_import"),
            Self::V1Import => write!(f, "v1_import"),
        }
    }
}

impl Default for ContentSyncJobKind {
    fn default() -> ContentSyncJobKind {
        Self::Sync
    }
}

