/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentSyncJobSummary : The most recent job for a source, as detail surfaces it. Prefer `ContentSyncJob` when reading a job by id. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentSyncJobSummary {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "kind")]
    pub kind: models::ContentSyncJobKind,
    #[serde(rename = "status")]
    pub status: models::ContentSyncJobStatus,
    /// Version token the job targeted, when one was named.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "phase", skip_serializing_if = "Option::is_none")]
    pub phase: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "startedAt", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "finishedAt", skip_serializing_if = "Option::is_none")]
    pub finished_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl ContentSyncJobSummary {
    /// The most recent job for a source, as detail surfaces it. Prefer `ContentSyncJob` when reading a job by id. 
    pub fn new(id: uuid::Uuid, kind: models::ContentSyncJobKind, status: models::ContentSyncJobStatus, created_at: chrono::DateTime<chrono::FixedOffset>) -> ContentSyncJobSummary {
        ContentSyncJobSummary {
            id,
            kind,
            status,
            version: None,
            phase: None,
            message: None,
            error: None,
            created_at,
            started_at: None,
            finished_at: None,
        }
    }
}

