/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentProcedureTemplate : One structured procedure template (Atomic test or custom). Platforms, executor, command, cleanup, and input args stay distinct — never a single flattened actions string (PLAN.md §3). 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentProcedureTemplate {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "sourceId")]
    pub source_id: uuid::Uuid,
    /// Version token. Atomic Red Team is rolling-head and always `current`. 
    #[serde(rename = "version")]
    pub version: String,
    /// Stable id within the source. Prefer upstream `auto_generated_guid`; otherwise `{technique}/{zero-based-index}` (documented in `docs/content-atomic.md`). 
    #[serde(rename = "externalId")]
    pub external_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    /// Supported platforms (`windows`, `linux`, `macos`, …).
    #[serde(rename = "platforms")]
    pub platforms: Vec<String>,
    /// Executor name (`powershell`, `command_prompt`, `sh`, `bash`, `manual`, …).
    #[serde(rename = "executor")]
    pub executor: String,
    #[serde(rename = "elevationRequired")]
    pub elevation_required: bool,
    /// Primary command or manual steps body.
    #[serde(rename = "command")]
    pub command: String,
    /// Cleanup command when present; empty string otherwise.
    #[serde(rename = "cleanup")]
    pub cleanup: String,
    #[serde(rename = "inputArgs")]
    pub input_args: Vec<models::ContentProcedureInputArg>,
    /// ATT&CK technique external ids this template maps to.
    #[serde(rename = "techniqueExternalIds")]
    pub technique_external_ids: Vec<String>,
    #[serde(rename = "dependencyExecutorName")]
    pub dependency_executor_name: String,
    /// Serialized dependency list when present (JSON array text). Empty string when the upstream test has no dependencies. 
    #[serde(rename = "dependencies")]
    pub dependencies: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl ContentProcedureTemplate {
    /// One structured procedure template (Atomic test or custom). Platforms, executor, command, cleanup, and input args stay distinct — never a single flattened actions string (PLAN.md §3). 
    pub fn new(id: uuid::Uuid, source_id: uuid::Uuid, version: String, external_id: String, name: String, description: String, platforms: Vec<String>, executor: String, elevation_required: bool, command: String, cleanup: String, input_args: Vec<models::ContentProcedureInputArg>, technique_external_ids: Vec<String>, dependency_executor_name: String, dependencies: String, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> ContentProcedureTemplate {
        ContentProcedureTemplate {
            id,
            source_id,
            version,
            external_id,
            name,
            description,
            platforms,
            executor,
            elevation_required,
            command,
            cleanup,
            input_args,
            technique_external_ids,
            dependency_executor_name,
            dependencies,
            created_at,
            updated_at,
        }
    }
}

