/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentAttackVersionCounts : Object counts by family for one ATT&CK version.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentAttackVersionCounts {
    #[serde(rename = "tactics")]
    pub tactics: i64,
    #[serde(rename = "techniques")]
    pub techniques: i64,
    #[serde(rename = "mitigations")]
    pub mitigations: i64,
    #[serde(rename = "groups")]
    pub groups: i64,
    #[serde(rename = "software")]
    pub software: i64,
    #[serde(rename = "dataSources")]
    pub data_sources: i64,
}

impl ContentAttackVersionCounts {
    /// Object counts by family for one ATT&CK version.
    pub fn new(tactics: i64, techniques: i64, mitigations: i64, groups: i64, software: i64, data_sources: i64) -> ContentAttackVersionCounts {
        ContentAttackVersionCounts {
            tactics,
            techniques,
            mitigations,
            groups,
            software,
            data_sources,
        }
    }
}

