/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreatedUser : A newly created account and where to send the person it belongs to. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatedUser {
    #[serde(rename = "user")]
    pub user: models::User,
    /// Where this installation is signed in to. There is no mail transport in this deployment, so nothing was sent: an administrator passes this on themselves, with the password they chose or with a note to use the single sign-on button.  It carries no credential and grants nothing — it is a link to the front door, and anybody may already know it. 
    #[serde(rename = "inviteUrl")]
    pub invite_url: String,
}

impl CreatedUser {
    /// A newly created account and where to send the person it belongs to. 
    pub fn new(user: models::User, invite_url: String) -> CreatedUser {
        CreatedUser {
            user,
            invite_url,
        }
    }
}

