/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEngagement {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "client", skip_serializing_if = "Option::is_none")]
    pub client: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Defaults to today when unset.
    #[serde(rename = "startsOn", skip_serializing_if = "Option::is_none")]
    pub starts_on: Option<chrono::NaiveDate>,
    /// Defaults to today when unset.
    #[serde(rename = "endsOn", skip_serializing_if = "Option::is_none")]
    pub ends_on: Option<chrono::NaiveDate>,
    /// ATT&CK version pin. Must pass attackpin.AssertPinned.
    #[serde(rename = "attackVersion")]
    pub attack_version: String,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::EngagementMode>,
    #[serde(rename = "autoRevealOnStart", skip_serializing_if = "Option::is_none")]
    pub auto_reveal_on_start: Option<bool>,
}

impl CreateEngagement {
    pub fn new(name: String, attack_version: String) -> CreateEngagement {
        CreateEngagement {
            name,
            client: None,
            description: None,
            starts_on: None,
            ends_on: None,
            attack_version,
            mode: None,
            auto_reveal_on_start: None,
        }
    }
}

