/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateStep {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "objective", skip_serializing_if = "Option::is_none")]
    pub objective: Option<String>,
    #[serde(rename = "techniqueId", skip_serializing_if = "Option::is_none")]
    pub technique_id: Option<String>,
    #[serde(rename = "subtechniqueId", skip_serializing_if = "Option::is_none")]
    pub subtechnique_id: Option<String>,
    #[serde(rename = "tacticId", skip_serializing_if = "Option::is_none")]
    pub tactic_id: Option<String>,
    /// When set, resolve the technique against the engagement's pinned ATT&CK version and snapshot display fields. Mutually exclusive with technique_id/subtechnique_id.
    #[serde(rename = "techniqueExternalId", skip_serializing_if = "Option::is_none")]
    pub technique_external_id: Option<String>,
    /// Structured procedure JSON.
    #[serde(rename = "procedure", skip_serializing_if = "Option::is_none")]
    pub procedure: Option<serde_json::Value>,
    #[serde(rename = "templateId", skip_serializing_if = "Option::is_none")]
    pub template_id: Option<String>,
    #[serde(rename = "targetAsset", skip_serializing_if = "Option::is_none")]
    pub target_asset: Option<String>,
    #[serde(rename = "tools", skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<String>>,
    #[serde(rename = "controlsInScope", skip_serializing_if = "Option::is_none")]
    pub controls_in_scope: Option<Vec<String>>,
}

impl CreateStep {
    pub fn new(name: String) -> CreateStep {
        CreateStep {
            name,
            objective: None,
            technique_id: None,
            subtechnique_id: None,
            tactic_id: None,
            technique_external_id: None,
            procedure: None,
            template_id: None,
            target_asset: None,
            tools: None,
            controls_in_scope: None,
        }
    }
}

