/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateReportShare : Body of POST /report-versions/{versionId}/shares.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateReportShare {
    /// Optional password gate. When set, must satisfy the account password policy (internal/authn/password): at least 12 characters, at most 128, and not a common password. Omit for a share with no gate. 
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// Optional expiry. After this time the share returns 404.
    #[serde(rename = "expiresAt", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Optional human-readable label.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Maximum number of claims. Omit for unlimited.
    #[serde(rename = "maxGrants", skip_serializing_if = "Option::is_none")]
    pub max_grants: Option<i32>,
}

impl CreateReportShare {
    /// Body of POST /report-versions/{versionId}/shares.
    pub fn new() -> CreateReportShare {
        CreateReportShare {
            password: None,
            expires_at: None,
            label: None,
            max_grants: None,
        }
    }
}

