/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateServiceTokenRequest : Body of `POST /auth/tokens`. The owner is the caller and is not a field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateServiceTokenRequest {
    /// How you will recognise this token when you come to revoke it.
    #[serde(rename = "name")]
    pub name: String,
    /// What the token may do. Repeats are accepted and stored once; a scope this server does not define is a `400` rather than a silently narrower token. 
    #[serde(rename = "scopes")]
    pub scopes: Vec<models::TokenScope>,
    /// Bind the token to one engagement. Omit for a token that may reach every engagement you can. It cannot widen what you may reach. 
    #[serde(rename = "engagementId", skip_serializing_if = "Option::is_none")]
    pub engagement_id: Option<uuid::Uuid>,
    /// When the token should stop working. Required, must be in the future, and at most one year out — `400` otherwise, naming the field. 
    #[serde(rename = "expiresAt")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
}

impl CreateServiceTokenRequest {
    /// Body of `POST /auth/tokens`. The owner is the caller and is not a field.
    pub fn new(name: String, scopes: Vec<models::TokenScope>, expires_at: chrono::DateTime<chrono::FixedOffset>) -> CreateServiceTokenRequest {
        CreateServiceTokenRequest {
            name,
            scopes,
            engagement_id: None,
            expires_at,
        }
    }
}

