/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateCustomDetectionRuleRequest : Body for creating a custom detection rule reference.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCustomDetectionRuleRequest {
    #[serde(rename = "externalId", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "techniqueExternalIds", skip_serializing_if = "Option::is_none")]
    pub technique_external_ids: Option<Vec<String>>,
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "logsource", skip_serializing_if = "Option::is_none")]
    pub logsource: Option<models::ContentDetectionLogsource>,
    #[serde(rename = "ruleYaml")]
    pub rule_yaml: String,
}

impl CreateCustomDetectionRuleRequest {
    /// Body for creating a custom detection rule reference.
    pub fn new(name: String, rule_yaml: String) -> CreateCustomDetectionRuleRequest {
        CreateCustomDetectionRuleRequest {
            external_id: None,
            name,
            description: None,
            technique_external_ids: None,
            level: None,
            status: None,
            logsource: None,
            rule_yaml,
        }
    }
}

