/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CurrentUser : The caller, as `GET /auth/me` reports them. It carries nothing about the session token: the cookie is the only place that value exists outside the client. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrentUser {
    /// The user's identifier — a UUIDv7, as every identifier here is.
    #[serde(rename = "id")]
    pub id: String,
    /// The address as it was typed when the account was created.
    #[serde(rename = "email")]
    pub email: String,
    /// The name to show for this person.
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "platformRole")]
    pub platform_role: models::PlatformRole,
    #[serde(rename = "mfa")]
    pub mfa: models::MfaState,
    /// Every engagement this person belongs to, and their role in it. An administrator's list is still only what they are a *member* of — their reach beyond it comes from `platformRole`, not from here. 
    #[serde(rename = "memberships")]
    pub memberships: Vec<models::EngagementMembership>,
    /// The double-submit CSRF token for this session (M1-005) — the same value as the `bl_csrf` cookie, which is where a browser client should read it from.  It is here for a client that has no cookie jar to read, and it is not a secret in the way the session token is: it authorizes nothing on its own. Absent for a caller authenticated by a service token, which is not subject to the check. 
    #[serde(rename = "csrfToken", skip_serializing_if = "Option::is_none")]
    pub csrf_token: Option<String>,
}

impl CurrentUser {
    /// The caller, as `GET /auth/me` reports them. It carries nothing about the session token: the cookie is the only place that value exists outside the client. 
    pub fn new(id: String, email: String, display_name: String, platform_role: models::PlatformRole, mfa: models::MfaState, memberships: Vec<models::EngagementMembership>) -> CurrentUser {
        CurrentUser {
            id,
            email,
            display_name,
            platform_role,
            mfa,
            memberships,
            csrf_token: None,
        }
    }
}

