/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DetectionCategory : Blue-side detection rating, ordinal 0–4.
/// Blue-side detection rating, ordinal 0–4.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DetectionCategory {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "telemetry")]
    Telemetry,
    #[serde(rename = "general")]
    General,
    #[serde(rename = "tactic")]
    Tactic,
    #[serde(rename = "technique")]
    Technique,

}

impl std::fmt::Display for DetectionCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::Telemetry => write!(f, "telemetry"),
            Self::General => write!(f, "general"),
            Self::Tactic => write!(f, "tactic"),
            Self::Technique => write!(f, "technique"),
        }
    }
}

impl Default for DetectionCategory {
    fn default() -> DetectionCategory {
        Self::None
    }
}

