/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DisableTotpRequest : Body of `DELETE /auth/mfa/totp`. The current password is required for the same reason `ChangePasswordRequest` asks for it. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisableTotpRequest {
    #[serde(rename = "currentPassword")]
    pub current_password: String,
}

impl DisableTotpRequest {
    /// Body of `DELETE /auth/mfa/totp`. The current password is required for the same reason `ChangePasswordRequest` asks for it. 
    pub fn new(current_password: String) -> DisableTotpRequest {
        DisableTotpRequest {
            current_password,
        }
    }
}

