/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EngagementMembership : One person's place in one engagement.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EngagementMembership {
    #[serde(rename = "engagementId")]
    pub engagement_id: String,
    #[serde(rename = "role")]
    pub role: models::EngagementRole,
    #[serde(rename = "addedAt")]
    pub added_at: chrono::DateTime<chrono::FixedOffset>,
}

impl EngagementMembership {
    /// One person's place in one engagement.
    pub fn new(engagement_id: String, role: models::EngagementRole, added_at: chrono::DateTime<chrono::FixedOffset>) -> EngagementMembership {
        EngagementMembership {
            engagement_id,
            role,
            added_at,
        }
    }
}

