/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EngagementMode : `standard`: both sides see the workbook. `blind`: red/lead decide what blue sees via per-step reveal. 
/// `standard`: both sides see the workbook. `blind`: red/lead decide what blue sees via per-step reveal. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EngagementMode {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "blind")]
    Blind,

}

impl std::fmt::Display for EngagementMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Standard => write!(f, "standard"),
            Self::Blind => write!(f, "blind"),
        }
    }
}

impl Default for EngagementMode {
    fn default() -> EngagementMode {
        Self::Standard
    }
}

