/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EngagementPage {
    #[serde(rename = "items")]
    pub items: Vec<models::Engagement>,
    /// Opaque cursor for the next page; null on the last.
    #[serde(rename = "nextCursor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<Option<String>>,
}

impl EngagementPage {
    pub fn new(items: Vec<models::Engagement>) -> EngagementPage {
        EngagementPage {
            items,
            next_cursor: None,
        }
    }
}

