/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Execution {
    /// UUIDv7.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "stepId")]
    pub step_id: uuid::Uuid,
    /// Optimistic-lock version. Incremented on every red or blue PATCH.
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "status")]
    pub status: models::ExecutionStatus,
    /// User id of the first red operator who moved this out of pending.
    #[serde(rename = "executedBy")]
    pub executed_by: String,
    #[serde(rename = "startedAt", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "endedAt", skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The command or payload that was executed.
    #[serde(rename = "commandRun")]
    pub command_run: String,
    /// The host that ran the attack.
    #[serde(rename = "sourceHost")]
    pub source_host: String,
    /// The host that received the attack.
    #[serde(rename = "targetHost")]
    pub target_host: String,
    /// Free-form notes from the red operator.
    #[serde(rename = "redNotes")]
    pub red_notes: String,
    #[serde(rename = "detectionCategory", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub detection_category: Option<Option<DetectionCategory>>,
    /// Qualifiers on the detection category.
    #[serde(rename = "detectionModifiers")]
    pub detection_modifiers: Vec<String>,
    #[serde(rename = "protection", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub protection: Option<Option<Protection>>,
    #[serde(rename = "detectedAt", skip_serializing_if = "Option::is_none")]
    pub detected_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Source of detection (e.g. \"Splunk\", \"Sentinel\").
    #[serde(rename = "detectingSource")]
    pub detecting_source: String,
    /// Reference to the detection rule that fired.
    #[serde(rename = "detectingRuleRef")]
    pub detecting_rule_ref: String,
    /// Alert severity (e.g. \"high\", \"medium\", \"low\").
    #[serde(rename = "alertSeverity")]
    pub alert_severity: String,
    /// Free-form notes from the blue operator.
    #[serde(rename = "blueNotes")]
    pub blue_notes: String,
    /// User id of the scorer.
    #[serde(rename = "scoredBy")]
    pub scored_by: String,
    #[serde(rename = "scoredAt", skip_serializing_if = "Option::is_none")]
    pub scored_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    /// Derived detection outcome from category × protection. Never stored; computed on read.
    #[serde(rename = "outcome", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub outcome: Option<Option<Outcome>>,
    /// Mean time to detect in seconds (detected_at − started_at). Computed on read; null when either timestamp is missing.
    #[serde(rename = "mttdSeconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mttd_seconds: Option<Option<i32>>,
}

impl Execution {
    pub fn new(id: uuid::Uuid, step_id: uuid::Uuid, version: i32, status: models::ExecutionStatus, executed_by: String, command_run: String, source_host: String, target_host: String, red_notes: String, detection_modifiers: Vec<String>, detecting_source: String, detecting_rule_ref: String, alert_severity: String, blue_notes: String, scored_by: String, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> Execution {
        Execution {
            id,
            step_id,
            version,
            status,
            executed_by,
            started_at: None,
            ended_at: None,
            command_run,
            source_host,
            target_host,
            red_notes,
            detection_category: None,
            detection_modifiers,
            protection: None,
            detected_at: None,
            detecting_source,
            detecting_rule_ref,
            alert_severity,
            blue_notes,
            scored_by,
            scored_at: None,
            created_at,
            updated_at,
            outcome: None,
            mttd_seconds: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DetectionCategory {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "telemetry")]
    Telemetry,
    #[serde(rename = "general")]
    General,
    #[serde(rename = "tactic")]
    Tactic,
    #[serde(rename = "technique")]
    Technique,
}

impl Default for DetectionCategory {
    fn default() -> DetectionCategory {
        Self::None
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Protection {
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "partial")]
    Partial,
    #[serde(rename = "not_blocked")]
    NotBlocked,
    #[serde(rename = "n/a")]
    NSlashA,
}

impl Default for Protection {
    fn default() -> Protection {
        Self::Blocked
    }
}
/// Derived detection outcome from category × protection. Never stored; computed on read.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Outcome {
    #[serde(rename = "prevented")]
    Prevented,
    #[serde(rename = "detected")]
    Detected,
    #[serde(rename = "not_detected")]
    NotDetected,
    #[serde(rename = "not_applicable")]
    NotApplicable,
}

impl Default for Outcome {
    fn default() -> Outcome {
        Self::Prevented
    }
}

