/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FieldError : One field-level validation failure.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FieldError {
    /// Path of the offending field within the request body.
    #[serde(rename = "field")]
    pub field: String,
    /// What is wrong with it, in English.
    #[serde(rename = "message")]
    pub message: String,
}

impl FieldError {
    /// One field-level validation failure.
    pub fn new(field: String, message: String) -> FieldError {
        FieldError {
            field,
            message,
        }
    }
}

