/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Finding {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "engagementId")]
    pub engagement_id: uuid::Uuid,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "severity")]
    pub severity: models::FindingSeverity,
    #[serde(rename = "recommendation")]
    pub recommendation: String,
    /// User id of the owner, or empty string.
    #[serde(rename = "owner")]
    pub owner: String,
    #[serde(rename = "status")]
    pub status: models::FindingStatus,
    /// The execution this finding was created from, if any.
    #[serde(rename = "createdFromExecution", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub created_from_execution: Option<Option<uuid::Uuid>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    /// Step ids linked to this finding.
    #[serde(rename = "stepIds")]
    pub step_ids: Vec<uuid::Uuid>,
}

impl Finding {
    pub fn new(id: uuid::Uuid, engagement_id: uuid::Uuid, title: String, description: String, severity: models::FindingSeverity, recommendation: String, owner: String, status: models::FindingStatus, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>, step_ids: Vec<uuid::Uuid>) -> Finding {
        Finding {
            id,
            engagement_id,
            title,
            description,
            severity,
            recommendation,
            owner,
            status,
            created_from_execution: None,
            created_at,
            updated_at,
            step_ids,
        }
    }
}

