/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Health : Health of the server and of everything it depends on. Reported with a 200 when `status` is `ok` and a 503 when it is `error`, so a monitor that only looks at the status code still gets the right answer. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Health {
    #[serde(rename = "status")]
    pub status: models::HealthState,
    #[serde(rename = "checks")]
    pub checks: models::HealthChecks,
}

impl Health {
    /// Health of the server and of everything it depends on. Reported with a 200 when `status` is `ok` and a 503 when it is `error`, so a monitor that only looks at the status code still gets the right answer. 
    pub fn new(status: models::HealthState, checks: models::HealthChecks) -> Health {
        Health {
            status,
            checks,
        }
    }
}

