/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportPlanWarning {
    /// The 1-based ordinal of the imported step within the scenario.
    #[serde(rename = "stepOrdinal")]
    pub step_ordinal: i32,
    /// Name of the imported step from the catalog.
    #[serde(rename = "stepName")]
    pub step_name: String,
    /// The technique external id that did not resolve.
    #[serde(rename = "techniqueExternalId")]
    pub technique_external_id: String,
    /// Human-readable explanation.
    #[serde(rename = "message")]
    pub message: String,
}

impl ImportPlanWarning {
    pub fn new(step_ordinal: i32, step_name: String, technique_external_id: String, message: String) -> ImportPlanWarning {
        ImportPlanWarning {
            step_ordinal,
            step_name,
            technique_external_id,
            message,
        }
    }
}

