/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LoginStatus : What a successful `POST /auth/login` established. A client must branch on this rather than assume that 200 means signed in. 
/// What a successful `POST /auth/login` established. A client must branch on this rather than assume that 200 means signed in. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LoginStatus {
    #[serde(rename = "authenticated")]
    Authenticated,
    #[serde(rename = "mfa_required")]
    MfaRequired,
    #[serde(rename = "mfa_enrolment_required")]
    MfaEnrolmentRequired,

}

impl std::fmt::Display for LoginStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Authenticated => write!(f, "authenticated"),
            Self::MfaRequired => write!(f, "mfa_required"),
            Self::MfaEnrolmentRequired => write!(f, "mfa_enrolment_required"),
        }
    }
}

impl Default for LoginStatus {
    fn default() -> LoginStatus {
        Self::Authenticated
    }
}

