/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MfaPolicy : The platform-wide half of the multi-factor requirement (M1-008). The other half is the per-user `mfaEnforced` flag, and the effective requirement for one person is the **or** of whichever apply — so turning both of these off does not release somebody an administrator has individually enforced.  Policy is evaluated before enrolment is looked at, which is the whole point: v1 asked \"have they enrolled?\" and so let anybody who skipped enrolment sign in with a password alone. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MfaPolicy {
    /// Every account that signs in with a local password must hold a second factor.
    #[serde(rename = "requiredForAll")]
    pub required_for_all: bool,
    /// Every account with the `admin` platform role must hold one. Implied by `requiredForAll`; the two are stored separately so that turning the wider one off does not silently release administrators too. 
    #[serde(rename = "requiredForAdmins")]
    pub required_for_admins: bool,
}

impl MfaPolicy {
    /// The platform-wide half of the multi-factor requirement (M1-008). The other half is the per-user `mfaEnforced` flag, and the effective requirement for one person is the **or** of whichever apply — so turning both of these off does not release somebody an administrator has individually enforced.  Policy is evaluated before enrolment is looked at, which is the whole point: v1 asked \"have they enrolled?\" and so let anybody who skipped enrolment sign in with a password alone. 
    pub fn new(required_for_all: bool, required_for_admins: bool) -> MfaPolicy {
        MfaPolicy {
            required_for_all,
            required_for_admins,
        }
    }
}

