/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NavigatorLayer {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "versions")]
    pub versions: models::NavigatorLayerVersions,
    #[serde(rename = "filters")]
    pub filters: models::NavigatorLayerFilters,
    #[serde(rename = "gradient")]
    pub gradient: models::NavigatorLayerGradient,
    #[serde(rename = "legendItems")]
    pub legend_items: Vec<models::NavigatorLegendItem>,
    #[serde(rename = "techniques")]
    pub techniques: Vec<models::NavigatorTechnique>,
    #[serde(rename = "showTacticRowBackground", skip_serializing_if = "Option::is_none")]
    pub show_tactic_row_background: Option<bool>,
    #[serde(rename = "tacticRowBackground", skip_serializing_if = "Option::is_none")]
    pub tactic_row_background: Option<String>,
    #[serde(rename = "selectTechniquesAcrossTactics", skip_serializing_if = "Option::is_none")]
    pub select_techniques_across_tactics: Option<bool>,
    #[serde(rename = "selectSubtechniquesWithParent", skip_serializing_if = "Option::is_none")]
    pub select_subtechniques_with_parent: Option<bool>,
}

impl NavigatorLayer {
    pub fn new(name: String, description: String, domain: String, versions: models::NavigatorLayerVersions, filters: models::NavigatorLayerFilters, gradient: models::NavigatorLayerGradient, legend_items: Vec<models::NavigatorLegendItem>, techniques: Vec<models::NavigatorTechnique>) -> NavigatorLayer {
        NavigatorLayer {
            name,
            description,
            domain,
            versions,
            filters,
            gradient,
            legend_items,
            techniques,
            show_tactic_row_background: None,
            tactic_row_background: None,
            select_techniques_across_tactics: None,
            select_subtechniques_with_parent: None,
        }
    }
}

