/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NavigatorTechnique {
    #[serde(rename = "techniqueID")]
    pub technique_id: String,
    #[serde(rename = "score")]
    pub score: i32,
    #[serde(rename = "color")]
    pub color: String,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Vec<models::NavigatorMetadata>>,
    #[serde(rename = "showSubtechniques", skip_serializing_if = "Option::is_none")]
    pub show_subtechniques: Option<bool>,
}

impl NavigatorTechnique {
    pub fn new(technique_id: String, score: i32, color: String, enabled: bool) -> NavigatorTechnique {
        NavigatorTechnique {
            technique_id,
            score,
            color,
            comment: None,
            enabled,
            metadata: None,
            show_subtechniques: None,
        }
    }
}

