/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewFinding {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "severity")]
    pub severity: models::FindingSeverity,
    #[serde(rename = "recommendation", skip_serializing_if = "Option::is_none")]
    pub recommendation: Option<String>,
    /// User id of the owner; defaults to caller when empty.
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::FindingStatus>,
    /// Optional execution id this finding originates from.
    #[serde(rename = "createdFromExecution", skip_serializing_if = "Option::is_none")]
    pub created_from_execution: Option<uuid::Uuid>,
}

impl NewFinding {
    pub fn new(title: String, description: String, severity: models::FindingSeverity) -> NewFinding {
        NewFinding {
            title,
            description,
            severity,
            recommendation: None,
            owner: None,
            status: None,
            created_from_execution: None,
        }
    }
}

