/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchScenario : Every field is optional; only the ones present are changed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchScenario {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "narrative", skip_serializing_if = "Option::is_none")]
    pub narrative: Option<String>,
    #[serde(rename = "threatActor", skip_serializing_if = "Option::is_none")]
    pub threat_actor: Option<String>,
}

impl PatchScenario {
    /// Every field is optional; only the ones present are changed.
    pub fn new() -> PatchScenario {
        PatchScenario {
            name: None,
            narrative: None,
            threat_actor: None,
        }
    }
}

