/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlatformRole : What somebody may do to this installation: `admin` manages users, content and every engagement; `member` takes part in the engagements they belong to. What they may do *inside* one is `EngagementRole`, and the two are deliberately not the same vocabulary. 
/// What somebody may do to this installation: `admin` manages users, content and every engagement; `member` takes part in the engagements they belong to. What they may do *inside* one is `EngagementRole`, and the two are deliberately not the same vocabulary. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PlatformRole {
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "member")]
    Member,

}

impl std::fmt::Display for PlatformRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Admin => write!(f, "admin"),
            Self::Member => write!(f, "member"),
        }
    }
}

impl Default for PlatformRole {
    fn default() -> PlatformRole {
        Self::Admin
    }
}

