/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PresenceEntry {
    /// The user's platform id.
    #[serde(rename = "userId")]
    pub user_id: uuid::Uuid,
    /// The user's display name.
    #[serde(rename = "displayName")]
    pub display_name: String,
    /// When this user's most recent heartbeat arrived.
    #[serde(rename = "lastSeenAt")]
    pub last_seen_at: chrono::DateTime<chrono::FixedOffset>,
    /// Number of active tabs/windows for this user in this engagement.
    #[serde(rename = "tabCount")]
    pub tab_count: i32,
    #[serde(rename = "focus", skip_serializing_if = "Option::is_none")]
    pub focus: Option<models::PresenceEntryFocus>,
}

impl PresenceEntry {
    pub fn new(user_id: uuid::Uuid, display_name: String, last_seen_at: chrono::DateTime<chrono::FixedOffset>, tab_count: i32) -> PresenceEntry {
        PresenceEntry {
            user_id,
            display_name,
            last_seen_at,
            tab_count,
            focus: None,
        }
    }
}

