/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProblemCode : Stable machine-readable error identifier. Clients switch on this, never on `detail` and never on the status alone.  Each code maps to exactly one HTTP status; the mapping lives in internal/httpapi/apierr and a test there asserts it (M0B-007). Adding a code means adding it in both places in the same change.  The reverse is *nearly* 1:1. A code may refine another — same status, more specific instruction — and `mfa_enrolment_required` is the one that does, refining `forbidden`. A client that does not know a refinement can always fall back to the code it refines, and internal/httpapi/apierr holds the refinement table that says which that is. 
/// Stable machine-readable error identifier. Clients switch on this, never on `detail` and never on the status alone.  Each code maps to exactly one HTTP status; the mapping lives in internal/httpapi/apierr and a test there asserts it (M0B-007). Adding a code means adding it in both places in the same change.  The reverse is *nearly* 1:1. A code may refine another — same status, more specific instruction — and `mfa_enrolment_required` is the one that does, refining `forbidden`. A client that does not know a refinement can always fall back to the code it refines, and internal/httpapi/apierr holds the refinement table that says which that is. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProblemCode {
    #[serde(rename = "validation_failed")]
    ValidationFailed,
    #[serde(rename = "unauthenticated")]
    Unauthenticated,
    #[serde(rename = "forbidden")]
    Forbidden,
    #[serde(rename = "mfa_enrolment_required")]
    MfaEnrolmentRequired,
    #[serde(rename = "not_found")]
    NotFound,
    #[serde(rename = "method_not_allowed")]
    MethodNotAllowed,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "rate_limited")]
    RateLimited,
    #[serde(rename = "payload_too_large")]
    PayloadTooLarge,
    #[serde(rename = "internal")]
    Internal,

}

impl std::fmt::Display for ProblemCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ValidationFailed => write!(f, "validation_failed"),
            Self::Unauthenticated => write!(f, "unauthenticated"),
            Self::Forbidden => write!(f, "forbidden"),
            Self::MfaEnrolmentRequired => write!(f, "mfa_enrolment_required"),
            Self::NotFound => write!(f, "not_found"),
            Self::MethodNotAllowed => write!(f, "method_not_allowed"),
            Self::Conflict => write!(f, "conflict"),
            Self::RateLimited => write!(f, "rate_limited"),
            Self::PayloadTooLarge => write!(f, "payload_too_large"),
            Self::Internal => write!(f, "internal"),
        }
    }
}

impl Default for ProblemCode {
    fn default() -> ProblemCode {
        Self::ValidationFailed
    }
}

