/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecoveryCodeRequest : Body of `POST /auth/mfa/recovery/verify`: one recovery code, as the person has it written down. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecoveryCodeRequest {
    /// The code, in any case, with or without the hyphens it was printed with. The bounds and the pattern here are a backstop that keeps obvious junk off an unauthenticated path — what a code actually is gets decided in one place, `internal/authn/recovery.Parse`, and anything that gets past this and fails there is refused as an incorrect code rather than as a malformed request. Two answers to one question is how the two definitions would drift apart. 
    #[serde(rename = "code")]
    pub code: String,
}

impl RecoveryCodeRequest {
    /// Body of `POST /auth/mfa/recovery/verify`: one recovery code, as the person has it written down. 
    pub fn new(code: String) -> RecoveryCodeRequest {
        RecoveryCodeRequest {
            code,
        }
    }
}

