/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Report {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "engagementId")]
    pub engagement_id: uuid::Uuid,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "clientName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_name: Option<Option<String>>,
    #[serde(rename = "logoBlobRef", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logo_blob_ref: Option<Option<String>>,
    /// Nullable JSON object with optional primary/secondary hex colours.
    #[serde(rename = "colours", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub colours: Option<Option<serde_json::Value>>,
    #[serde(rename = "createdBy")]
    pub created_by: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Option<String>>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    /// How many draft blocks the report holds. Always present, including on list endpoints, which omit `blocks` itself — a list row that wants to show a count must read this rather than measuring `blocks`.
    #[serde(rename = "blockCount")]
    pub block_count: i32,
    /// Draft blocks in ordinal order. Present in GET /reports/{reportId} responses; absent from list endpoints.
    #[serde(rename = "blocks", skip_serializing_if = "Option::is_none")]
    pub blocks: Option<Vec<models::ReportBlock>>,
}

impl Report {
    pub fn new(id: uuid::Uuid, engagement_id: uuid::Uuid, title: String, created_by: String, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>, block_count: i32) -> Report {
        Report {
            id,
            engagement_id,
            title,
            client_name: None,
            logo_blob_ref: None,
            colours: None,
            created_by,
            created_at,
            updated_by: None,
            updated_at,
            block_count,
            blocks: None,
        }
    }
}

