/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReportBranding : Install-wide default branding for report generation. Every field has a built-in fallback so a fresh deployment produces readable output without configuration. Per-report overrides (client name, logo, colours) take precedence over these defaults; the resolution order is defined in docs/reporting.md. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportBranding {
    /// The firm or team name displayed in report headers and footers.
    #[serde(rename = "firmName")]
    pub firm_name: String,
    /// Primary brand colour as a hex triplet.
    #[serde(rename = "primaryColor")]
    pub primary_color: String,
    /// Secondary brand colour as a hex triplet.
    #[serde(rename = "secondaryColor")]
    pub secondary_color: String,
    /// Content-addressed blob reference for the logo image. Null means no logo is configured. Set this via POST /settings/report-branding/logo which returns the blob reference. 
    #[serde(rename = "logoBlobRef", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logo_blob_ref: Option<Option<String>>,
}

impl ReportBranding {
    /// Install-wide default branding for report generation. Every field has a built-in fallback so a fresh deployment produces readable output without configuration. Per-report overrides (client name, logo, colours) take precedence over these defaults; the resolution order is defined in docs/reporting.md. 
    pub fn new(firm_name: String, primary_color: String, secondary_color: String) -> ReportBranding {
        ReportBranding {
            firm_name,
            primary_color,
            secondary_color,
            logo_blob_ref: None,
        }
    }
}

