/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportVersion {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "reportId")]
    pub report_id: uuid::Uuid,
    #[serde(rename = "ordinal")]
    pub ordinal: i32,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "publishedBy")]
    pub published_by: String,
    #[serde(rename = "publishedAt")]
    pub published_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "includeEvidence")]
    pub include_evidence: bool,
    /// Always 'lead_full' for published versions.
    #[serde(rename = "blindScope")]
    pub blind_scope: String,
    #[serde(rename = "contentSha256", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content_sha256: Option<Option<String>>,
    #[serde(rename = "pdfSha256", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pdf_sha256: Option<Option<String>>,
}

impl ReportVersion {
    pub fn new(id: uuid::Uuid, report_id: uuid::Uuid, ordinal: i32, title: String, published_by: String, published_at: chrono::DateTime<chrono::FixedOffset>, include_evidence: bool, blind_scope: String) -> ReportVersion {
        ReportVersion {
            id,
            report_id,
            ordinal,
            title,
            published_by,
            published_at,
            include_evidence,
            blind_scope,
            content_sha256: None,
            pdf_sha256: None,
        }
    }
}

