/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportShareInfo {
    /// Whether the share exists and is active.
    #[serde(rename = "exists")]
    pub exists: bool,
    /// Whether the share requires a password.
    #[serde(rename = "passwordRequired", skip_serializing_if = "Option::is_none")]
    pub password_required: Option<bool>,
    /// Whether the current user has already claimed this share.
    #[serde(rename = "alreadyClaimed", skip_serializing_if = "Option::is_none")]
    pub already_claimed: Option<bool>,
    /// The share's label, if set.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl ReportShareInfo {
    pub fn new(exists: bool) -> ReportShareInfo {
        ReportShareInfo {
            exists,
            password_required: None,
            already_claimed: None,
            label: None,
        }
    }
}

