/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportShare {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "versionId")]
    pub version_id: uuid::Uuid,
    /// Whether this share requires a password.
    #[serde(rename = "passwordProtected", skip_serializing_if = "Option::is_none")]
    pub password_protected: Option<bool>,
    #[serde(rename = "expiresAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "revokedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "createdBy")]
    pub created_by: String,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    /// Maximum number of grants, or null for unlimited.
    #[serde(rename = "maxGrants", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_grants: Option<Option<i32>>,
    /// Current number of non-revoked grants.
    #[serde(rename = "grantCount", skip_serializing_if = "Option::is_none")]
    pub grant_count: Option<i32>,
    /// Grants for this share. Present in list endpoints.
    #[serde(rename = "grants", skip_serializing_if = "Option::is_none")]
    pub grants: Option<Vec<models::ReportShareGrant>>,
}

impl ReportShare {
    pub fn new(id: uuid::Uuid, version_id: uuid::Uuid, created_by: String, created_at: chrono::DateTime<chrono::FixedOffset>) -> ReportShare {
        ReportShare {
            id,
            version_id,
            password_protected: None,
            expires_at: None,
            revoked_at: None,
            created_by,
            created_at,
            label: None,
            max_grants: None,
            grant_count: None,
            grants: None,
        }
    }
}

