/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Scenario {
    /// UUIDv7.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "engagementId")]
    pub engagement_id: uuid::Uuid,
    /// 1-based dense position; UI order.
    #[serde(rename = "ordinal")]
    pub ordinal: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "narrative")]
    pub narrative: String,
    #[serde(rename = "source")]
    pub source: models::ScenarioSource,
    #[serde(rename = "threatActor", skip_serializing_if = "Option::is_none")]
    pub threat_actor: Option<String>,
    /// External reference (CTID plan id, import key).
    #[serde(rename = "sourceRef", skip_serializing_if = "Option::is_none")]
    pub source_ref: Option<String>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl Scenario {
    pub fn new(id: uuid::Uuid, engagement_id: uuid::Uuid, ordinal: i32, name: String, narrative: String, source: models::ScenarioSource, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> Scenario {
        Scenario {
            id,
            engagement_id,
            ordinal,
            name,
            narrative,
            source,
            threat_actor: None,
            source_ref: None,
            created_at,
            updated_at,
        }
    }
}

