/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScenarioSource : Provenance of a scenario. `manual` is authored here; `ctid` and `imported` come from content.
/// Provenance of a scenario. `manual` is authored here; `ctid` and `imported` come from content.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScenarioSource {
    #[serde(rename = "manual")]
    Manual,
    #[serde(rename = "ctid")]
    Ctid,
    #[serde(rename = "imported")]
    Imported,

}

impl std::fmt::Display for ScenarioSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Manual => write!(f, "manual"),
            Self::Ctid => write!(f, "ctid"),
            Self::Imported => write!(f, "imported"),
        }
    }
}

impl Default for ScenarioSource {
    fn default() -> ScenarioSource {
        Self::Manual
    }
}

