/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServiceTokens : A set of service tokens, newest first. Both listings return it — your own (`GET /auth/tokens`) and, for an administrator, one account's (`GET /users/{userId}/tokens`) — so the two cannot come to describe a token differently. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceTokens {
    #[serde(rename = "items")]
    pub items: Vec<models::ServiceToken>,
}

impl ServiceTokens {
    /// A set of service tokens, newest first. Both listings return it — your own (`GET /auth/tokens`) and, for an administrator, one account's (`GET /users/{userId}/tokens`) — so the two cannot come to describe a token differently. 
    pub fn new(items: Vec<models::ServiceToken>) -> ServiceTokens {
        ServiceTokens {
            items,
        }
    }
}

