/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Session : One browser this account is signed in on, as `GET /auth/sessions` reports it.  Everything here is what the server observed when the session was issued and last used. Nothing in it identifies the token: the value in the cookie is not stored — only a hash of it is — so there is no field to leave out by mistake. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Session {
    /// The session's identifier, and what `DELETE /auth/sessions/{sessionId}` takes.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Whether this is the session the request was made on. Exactly one row in a response has it, and it is the row a client marks as \"this device\" rather than offering to revoke. 
    #[serde(rename = "current")]
    pub current: bool,
    /// When this session was issued — the sign-in it belongs to.
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// When a request last arrived on it, to within a minute: recording every request would put a write in front of every read, so it is written back at most once a minute (`internal/authn/session`). 
    #[serde(rename = "lastSeenAt")]
    pub last_seen_at: chrono::DateTime<chrono::FixedOffset>,
    /// The absolute expiry. Nothing extends it, so a session ends at this moment however busy it has been. It may end sooner by going idle, which is a policy this document does not carry — a client that wanted to render \"expires in\" should say \"expires by\". 
    #[serde(rename = "expiresAt")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
    /// Whether a second factor was presented for *this* session, as opposed to at some point in this account's past (M1-006). A deployment that has just turned the requirement on can have live sessions where this is false. 
    #[serde(rename = "mfaSatisfied")]
    pub mfa_satisfied: bool,
    /// The client address the session was issued to, as the server saw it (`internal/httpapi.clientIP`). Absent when the request did not carry one. It is what somebody scans the list for, and it is the server's observation rather than anything the client claimed. 
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    /// The `User-Agent` the session was issued to, absent when the request sent none. Attacker-controlled, like every request header: render it as text and never as markup. 
    #[serde(rename = "userAgent", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
}

impl Session {
    /// One browser this account is signed in on, as `GET /auth/sessions` reports it.  Everything here is what the server observed when the session was issued and last used. Nothing in it identifies the token: the value in the cookie is not stored — only a hash of it is — so there is no field to leave out by mistake. 
    pub fn new(id: uuid::Uuid, current: bool, created_at: chrono::DateTime<chrono::FixedOffset>, last_seen_at: chrono::DateTime<chrono::FixedOffset>, expires_at: chrono::DateTime<chrono::FixedOffset>, mfa_satisfied: bool) -> Session {
        Session {
            id,
            current,
            created_at,
            last_seen_at,
            expires_at,
            mfa_satisfied,
            ip: None,
            user_agent: None,
        }
    }
}

