/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SsoProvider : One single sign-on button.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SsoProvider {
    /// Which protocol this provider speaks.
    #[serde(rename = "id")]
    pub id: Id,
    /// What to write on the button. It names the protocol rather than the provider: the issuer URL is configuration, and putting it on a public page would tell an unauthenticated caller which directory this organization uses. 
    #[serde(rename = "label")]
    pub label: String,
    /// Where to send the browser to begin. A path within this deployment, relative to the API base — navigate to it, do not fetch it. 
    #[serde(rename = "startUrl")]
    pub start_url: String,
}

impl SsoProvider {
    /// One single sign-on button.
    pub fn new(id: Id, label: String, start_url: String) -> SsoProvider {
        SsoProvider {
            id,
            label,
            start_url,
        }
    }
}
/// Which protocol this provider speaks.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Id {
    #[serde(rename = "oidc")]
    Oidc,
    #[serde(rename = "saml")]
    Saml,
}

impl Default for Id {
    fn default() -> Id {
        Self::Oidc
    }
}

