/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TotpCodeRequest : A six-digit code from an authenticator app. The same body confirms an enrolment and completes a sign-in. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TotpCodeRequest {
    /// The code as the app shows it, without the space some apps put in the middle. Six digits is the whole vocabulary — a value that is not six digits is rejected as malformed rather than counted as a guess. 
    #[serde(rename = "code")]
    pub code: String,
}

impl TotpCodeRequest {
    /// A six-digit code from an authenticator app. The same body confirms an enrolment and completes a sign-in. 
    pub fn new(code: String) -> TotpCodeRequest {
        TotpCodeRequest {
            code,
        }
    }
}

