/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateSelfRequest : Body of `PATCH /users/me`. One field, and that is the design: a schema with no `platformRole` in it is a request that cannot ask for one, which is a stronger guarantee than a handler that declines to honour it (PLAN.md §4). 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSelfRequest {
    #[serde(rename = "displayName")]
    pub display_name: String,
}

impl UpdateSelfRequest {
    /// Body of `PATCH /users/me`. One field, and that is the design: a schema with no `platformRole` in it is a request that cannot ask for one, which is a stronger guarantee than a handler that declines to honour it (PLAN.md §4). 
    pub fn new(display_name: String) -> UpdateSelfRequest {
        UpdateSelfRequest {
            display_name,
        }
    }
}

