/*
 * Blacklight API
 *
 * The HTTP API of a Blacklight deployment. Single-tenant, single-node: this document describes the one server the SPA talks to, and the same endpoints are the supported integration surface for scripts and CI.  All timestamps are UTC, RFC 3339. All identifiers are UUIDv7 strings — sortable by creation time, so `ORDER BY id` is a stable tiebreaker. Errors are RFC 9457 problem documents; see the `Problem` schema. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Version : Build identity of the running binary, stamped at link time. Every field is populated: an unstamped build reports a placeholder rather than an empty string. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Version {
    /// Release identifier from `git describe`, or `dev` for an unstamped build.
    #[serde(rename = "version")]
    pub version: String,
    /// Git commit the binary was built from, or `unknown`.
    #[serde(rename = "commit")]
    pub commit: String,
    /// UTC build timestamp, RFC 3339 — or the literal `unknown` for a build without version stamping. Deliberately not `format: date-time`, because it is not always a timestamp and a client must not assume it parses. 
    #[serde(rename = "buildDate")]
    pub build_date: String,
}

impl Version {
    /// Build identity of the running binary, stamped at link time. Every field is populated: an unstamped build reports a placeholder rather than an empty string. 
    pub fn new(version: String, commit: String, build_date: String) -> Version {
        Version {
            version,
            commit,
            build_date,
        }
    }
}

