package atomic

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// Catalog is the normalized Atomic library for one rolling-head sync.
//
// It is a single [content.Object] so the runner's item_count prefers
// [Catalog.ItemCount] over len(objects).
type Catalog struct {
	Templates []Template
}

// ItemCount is the procedure template total written for this sync.
func (c *Catalog) ItemCount() int64 { return int64(len(c.Templates)) }

// Template is one normalized Atomic test ready for Apply.
type Template struct {
	ExternalID             string
	Name                   string
	Description            string
	Platforms              []string
	Executor               string
	ElevationRequired      bool
	Command                string
	Cleanup                string
	InputArgs              []InputArg
	TechniqueExternalIDs   []string
	DependencyExecutorName string
	Dependencies           string // JSON array text, or ""
}

// InputArg is one structured input argument (never flattened into command).
type InputArg struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Type        string `json:"type"`
	Default     string `json:"default"`
}

func normalize(doc *atomicDoc) (*Catalog, error) {
	if doc == nil {
		return nil, fmt.Errorf("atomic: normalize: nil document")
	}
	cat := &Catalog{Templates: make([]Template, 0, 32)}
	seen := make(map[string]string, 32) // external_id → source path

	for _, f := range doc.Files {
		tech := strings.TrimSpace(f.AttackTechnique)
		if tech == "" {
			return nil, fmt.Errorf("atomic: normalize: %s: empty attack_technique", f.Path)
		}
		for i, raw := range f.Tests {
			name := strings.TrimSpace(raw.Name)
			if name == "" {
				return nil, fmt.Errorf("atomic: normalize: %s test[%d]: missing name", f.Path, i)
			}
			extID := externalID(tech, i, raw.AutoGeneratedGUID)
			if prev, ok := seen[extID]; ok {
				return nil, fmt.Errorf(
					"atomic: normalize: duplicate external_id %q in %s and %s",
					extID, prev, f.Path,
				)
			}
			seen[extID] = f.Path

			executor := strings.TrimSpace(raw.Executor.Name)
			if executor == "" {
				return nil, fmt.Errorf("atomic: normalize: %s %q: missing executor.name", f.Path, name)
			}

			command := strings.TrimSpace(raw.Executor.Command)
			if command == "" {
				// Manual executor uses steps instead of command.
				command = strings.TrimSpace(raw.Executor.Steps)
			}
			cleanup := strings.TrimSpace(raw.Executor.CleanupCommand)

			platforms := normalizePlatforms(raw.SupportedPlatforms)
			if len(platforms) == 0 {
				return nil, fmt.Errorf("atomic: normalize: %s %q: supported_platforms is empty", f.Path, name)
			}

			args, err := normalizeInputArgs(raw.InputArguments)
			if err != nil {
				return nil, fmt.Errorf("atomic: normalize: %s %q: input_arguments: %w", f.Path, name, err)
			}

			depsText, err := normalizeDependencies(raw.Dependencies)
			if err != nil {
				return nil, fmt.Errorf("atomic: normalize: %s %q: dependencies: %w", f.Path, name, err)
			}

			cat.Templates = append(cat.Templates, Template{
				ExternalID:             extID,
				Name:                   name,
				Description:            strings.TrimSpace(raw.Description),
				Platforms:              platforms,
				Executor:               executor,
				ElevationRequired:      raw.Executor.ElevationRequired,
				Command:                command,
				Cleanup:                cleanup,
				InputArgs:              args,
				TechniqueExternalIDs:   []string{tech},
				DependencyExecutorName: strings.TrimSpace(raw.DependencyExecutorName),
				Dependencies:           depsText,
			})
		}
	}

	if len(cat.Templates) == 0 {
		return nil, fmt.Errorf("atomic: normalize: zero tests parsed")
	}
	return cat, nil
}

// externalID prefers upstream auto_generated_guid; otherwise derives a stable
// key from technique + zero-based index so re-sync upserts rather than
// duplicates. Documented in docs/content-atomic.md.
func externalID(technique string, index int, guid string) string {
	guid = strings.TrimSpace(guid)
	if guid != "" {
		return guid
	}
	return fmt.Sprintf("%s/%d", technique, index)
}

func normalizePlatforms(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := make([]string, 0, len(in))
	seen := make(map[string]struct{}, len(in))
	for _, p := range in {
		p = strings.ToLower(strings.TrimSpace(p))
		if p == "" {
			continue
		}
		if _, ok := seen[p]; ok {
			continue
		}
		seen[p] = struct{}{}
		out = append(out, p)
	}
	return out
}

func normalizeInputArgs(in map[string]rawInputArg) ([]InputArg, error) {
	if len(in) == 0 {
		return []InputArg{}, nil
	}
	// Stable order: sort by name so Apply is deterministic.
	names := make([]string, 0, len(in))
	for name := range in {
		names = append(names, name)
	}
	// tiny insertion sort — avoid pulling sort for a few keys
	for i := 1; i < len(names); i++ {
		j := i
		for j > 0 && names[j-1] > names[j] {
			names[j-1], names[j] = names[j], names[j-1]
			j--
		}
	}
	out := make([]InputArg, 0, len(names))
	for _, name := range names {
		arg := in[name]
		out = append(out, InputArg{
			Name:        name,
			Description: strings.TrimSpace(arg.Description),
			Type:        strings.TrimSpace(arg.Type),
			Default:     anyString(arg.Default),
		})
	}
	return out, nil
}

func normalizeDependencies(in []rawDependency) (string, error) {
	if len(in) == 0 {
		return "", nil
	}
	type depJSON struct {
		Description      string `json:"description"`
		PrereqCommand    string `json:"prereq_command"`
		GetPrereqCommand string `json:"get_prereq_command"`
	}
	out := make([]depJSON, 0, len(in))
	for _, d := range in {
		out = append(out, depJSON{
			Description:      strings.TrimSpace(d.Description),
			PrereqCommand:    strings.TrimSpace(d.PrereqCommand),
			GetPrereqCommand: strings.TrimSpace(d.GetPrereqCommand),
		})
	}
	raw, err := json.Marshal(out)
	if err != nil {
		return "", err
	}
	return string(raw), nil
}

func anyString(v any) string {
	switch t := v.(type) {
	case nil:
		return ""
	case string:
		return t
	case bool:
		if t {
			return "true"
		}
		return "false"
	case int:
		return strconv.Itoa(t)
	case int64:
		return strconv.FormatInt(t, 10)
	case float64:
		// YAML numbers often decode as float64.
		if t == float64(int64(t)) {
			return strconv.FormatInt(int64(t), 10)
		}
		return strconv.FormatFloat(t, 'f', -1, 64)
	default:
		return fmt.Sprint(t)
	}
}
