package atomic

import (
	"archive/tar"
	"archive/zip"
	"bytes"
	"compress/gzip"
	"errors"
	"fmt"
	"io"
	"path"
	"strings"

	"gopkg.in/yaml.v3"
)

// atomicDoc is the adapter-private AST: one entry per technique YAML file.
type atomicDoc struct {
	Files []atomicFile
}

// atomicFile is one parsed atomics/Txxxx/Txxxx.yaml document.
type atomicFile struct {
	Path            string
	AttackTechnique string
	DisplayName     string
	Tests           []rawAtomicTest
}

// rawAtomicTest is the upstream YAML shape for one atomic_tests entry.
type rawAtomicTest struct {
	Name                   string                 `yaml:"name"`
	AutoGeneratedGUID      string                 `yaml:"auto_generated_guid"`
	Description            string                 `yaml:"description"`
	SupportedPlatforms     []string               `yaml:"supported_platforms"`
	InputArguments         map[string]rawInputArg `yaml:"input_arguments"`
	DependencyExecutorName string                 `yaml:"dependency_executor_name"`
	Dependencies           []rawDependency        `yaml:"dependencies"`
	Executor               rawExecutor            `yaml:"executor"`
}

type rawInputArg struct {
	Description string `yaml:"description"`
	Type        string `yaml:"type"`
	Default     any    `yaml:"default"`
}

type rawDependency struct {
	Description      string `yaml:"description"`
	PrereqCommand    string `yaml:"prereq_command"`
	GetPrereqCommand string `yaml:"get_prereq_command"`
}

type rawExecutor struct {
	Name              string `yaml:"name"`
	ElevationRequired bool   `yaml:"elevation_required"`
	Command           string `yaml:"command"`
	CleanupCommand    string `yaml:"cleanup_command"`
	Steps             string `yaml:"steps"` // manual executor
}

type techniqueYAML struct {
	AttackTechnique string          `yaml:"attack_technique"`
	DisplayName     string          `yaml:"display_name"`
	AtomicTests     []rawAtomicTest `yaml:"atomic_tests"`
}

func parseAtomics(raw []byte) (*atomicDoc, error) {
	files, err := extractAtomicYAML(raw)
	if err != nil {
		return nil, fmt.Errorf("atomic: parse: %w", err)
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("atomic: parse: archive contains no atomics YAML")
	}

	doc := &atomicDoc{Files: make([]atomicFile, 0, len(files))}
	for _, f := range files {
		var tech techniqueYAML
		dec := yaml.NewDecoder(bytes.NewReader(f.Body))
		dec.KnownFields(false)
		if err := dec.Decode(&tech); err != nil {
			return nil, fmt.Errorf("atomic: parse: %s: %w", f.Path, err)
		}
		tech.AttackTechnique = strings.TrimSpace(tech.AttackTechnique)
		if tech.AttackTechnique == "" {
			return nil, fmt.Errorf("atomic: parse: %s: missing attack_technique", f.Path)
		}
		if len(tech.AtomicTests) == 0 {
			// Empty tests array is schema drift / unusable file — fail loud.
			return nil, fmt.Errorf("atomic: parse: %s: atomic_tests is empty", f.Path)
		}
		doc.Files = append(doc.Files, atomicFile{
			Path:            f.Path,
			AttackTechnique: tech.AttackTechnique,
			DisplayName:     strings.TrimSpace(tech.DisplayName),
			Tests:           tech.AtomicTests,
		})
	}
	return doc, nil
}

type namedBytes struct {
	Path string
	Body []byte
}

// extractAtomicYAML returns technique YAML payloads from a zip/tar archive or
// a single bare YAML document. Paths must look like atomics/Txxxx/Txxxx.yaml
// (with optional repo-root prefix from GitHub archives).
func extractAtomicYAML(raw []byte) ([]namedBytes, error) {
	trim := bytes.TrimSpace(raw)
	if len(trim) == 0 {
		return nil, fmt.Errorf("empty payload")
	}
	// Bare YAML (single technique file) — useful for tiny fixtures.
	if looksLikeYAML(trim) {
		return []namedBytes{{Path: "inline.yaml", Body: trim}}, nil
	}
	// zip magic
	if len(raw) >= 4 && raw[0] == 'P' && raw[1] == 'K' {
		return extractYAMLFromZip(raw)
	}
	// gzip magic
	if len(raw) >= 2 && raw[0] == 0x1f && raw[1] == 0x8b {
		gr, err := gzip.NewReader(bytes.NewReader(raw))
		if err != nil {
			return nil, fmt.Errorf("gzip: %w", err)
		}
		defer gr.Close()
		ungzipped, err := io.ReadAll(gr)
		if err != nil {
			return nil, fmt.Errorf("gzip read: %w", err)
		}
		if looksLikeYAML(bytes.TrimSpace(ungzipped)) {
			return []namedBytes{{Path: "inline.yaml", Body: bytes.TrimSpace(ungzipped)}}, nil
		}
		return extractYAMLFromTar(ungzipped)
	}
	if looksLikeTar(raw) {
		return extractYAMLFromTar(raw)
	}
	return nil, fmt.Errorf("unrecognized payload (not YAML, zip, or tar.gz)")
}

func looksLikeYAML(b []byte) bool {
	if len(b) == 0 {
		return false
	}
	// STIX/JSON starts with { or [; Atomic YAML starts with a key or ---.
	if b[0] == '{' || b[0] == '[' {
		return false
	}
	s := string(b)
	return strings.Contains(s, "attack_technique:") || strings.Contains(s, "atomic_tests:")
}

func extractYAMLFromZip(raw []byte) ([]namedBytes, error) {
	zr, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		return nil, fmt.Errorf("zip: %w", err)
	}
	var out []namedBytes
	for _, f := range zr.File {
		if f.FileInfo().IsDir() {
			continue
		}
		if !isAtomicYAMLPath(f.Name) {
			continue
		}
		rc, err := f.Open()
		if err != nil {
			return nil, fmt.Errorf("zip open %s: %w", f.Name, err)
		}
		body, err := io.ReadAll(rc)
		_ = rc.Close()
		if err != nil {
			return nil, fmt.Errorf("zip read %s: %w", f.Name, err)
		}
		out = append(out, namedBytes{Path: f.Name, Body: body})
	}
	return out, nil
}

func extractYAMLFromTar(raw []byte) ([]namedBytes, error) {
	tr := tar.NewReader(bytes.NewReader(raw))
	var out []namedBytes
	for {
		hdr, err := tr.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("tar: %w", err)
		}
		if hdr.Typeflag != tar.TypeReg {
			continue
		}
		if !isAtomicYAMLPath(hdr.Name) {
			continue
		}
		body, err := io.ReadAll(tr)
		if err != nil {
			return nil, fmt.Errorf("tar read %s: %w", hdr.Name, err)
		}
		out = append(out, namedBytes{Path: hdr.Name, Body: body})
	}
	return out, nil
}

func looksLikeTar(raw []byte) bool {
	// ustar magic at offset 257
	if len(raw) < 262 {
		return false
	}
	return string(raw[257:262]) == "ustar"
}

// isAtomicYAMLPath accepts:
//
//	atomics/T1059.001/T1059.001.yaml
//	atomic-red-team-master/atomics/T1059/T1059.yaml
//	T1059.yaml (fixture convenience)
//
// Skips Indexes, src/, bin/, and non-yaml.
func isAtomicYAMLPath(name string) bool {
	name = strings.ReplaceAll(name, "\\", "/")
	base := path.Base(name)
	if !strings.HasSuffix(strings.ToLower(base), ".yaml") && !strings.HasSuffix(strings.ToLower(base), ".yml") {
		return false
	}
	// Skip known non-test YAML.
	lower := strings.ToLower(name)
	if strings.Contains(lower, "/src/") || strings.Contains(lower, "/bin/") {
		return false
	}
	if strings.Contains(lower, "index.yaml") || strings.Contains(lower, "indexes/") {
		return false
	}
	// Prefer atomics/ tree; also accept a bare Txxxx.yaml for fixtures.
	if strings.Contains(lower, "/atomics/") || strings.HasPrefix(lower, "atomics/") {
		return true
	}
	// Fixture convenience: top-level T####.yaml
	b := strings.TrimSuffix(strings.TrimSuffix(base, ".yaml"), ".yml")
	if len(b) >= 5 && (b[0] == 'T' || b[0] == 't') {
		return true
	}
	return false
}
