package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/bryanster/blacklight/internal/authz"
)

// docPath is docs/authz.md, from this package's directory.
var docPath = filepath.Join("..", "..", "..", "docs", "authz.md")

// TestTheCommittedDocumentIsCurrent. CI's drift gate catches this too, by
// running `make generate` and looking at `git status` — but a failure there
// arrives minutes later and names a diff rather than a cause. Here it arrives
// in `make test` and says what to run.
func TestTheCommittedDocumentIsCurrent(t *testing.T) {
	committed, err := os.ReadFile(docPath)
	if err != nil {
		t.Fatalf("reading the committed document: %v", err)
	}

	if string(committed) != string(render()) {
		t.Error("docs/authz.md is not what the rule table renders. Run `make generate` and commit the result.")
	}
}

// TestEveryActionAppearsInTheDocument: the point of generating this page is
// that it is the whole model. A rule the renderer silently drops — because its
// resource type is neither platform- nor engagement-owned, say — would be a
// permission nobody reviewed.
func TestEveryActionAppearsInTheDocument(t *testing.T) {
	rendered := string(render())

	for _, rule := range authz.Rules() {
		if !strings.Contains(rendered, "`"+rule.Name+"`") {
			t.Errorf("docs/authz.md does not mention %s", rule.Name)
		}
		if !strings.Contains(rendered, rule.Summary) {
			t.Errorf("docs/authz.md does not carry %s's summary", rule.Name)
		}
	}
}

// TestEveryGuardIsDescribed. A guard is the only way a ✓ in the tables is
// conditional, so an undescribed one is a table that is quietly wrong.
func TestEveryGuardIsDescribed(t *testing.T) {
	for _, rule := range authz.Rules() {
		if rule.Guard == authz.GuardNone {
			continue
		}
		if _, described := guardDescriptions[rule.Guard]; !described {
			t.Errorf("the %s guard on %s has no description in guardDescriptions", rule.Guard, rule.Name)
		}
	}
}

// TestTheDocumentSaysItIsGenerated, so that the next person to want a change
// edits the table rather than the page.
func TestTheDocumentSaysItIsGenerated(t *testing.T) {
	if first, _, _ := strings.Cut(string(render()), "\n"); !strings.Contains(first, "Generated by") {
		t.Errorf("the first line does not say the file is generated: %q", first)
	}
}
