// Command authzdoc renders docs/authz.md from the rule table in
// internal/authz, so that the documented permission model and the enforced one
// cannot be different things.
//
// It is a separate package from authz for one reason: authz must import
// nothing that could tempt a rule into doing I/O (M1-012), and a generator
// writes files. Run it with `make generate`.
package main

import (
	"fmt"
	"strings"

	"github.com/bryanster/blacklight/internal/authz"
)

// held and notHeld are the table cells. Symbols rather than words because the
// point of a matrix is that a wrong cell is visible from across the room.
const (
	held    = "✓"
	notHeld = "·"
)

// render returns the whole of docs/authz.md.
func render() []byte {
	var doc strings.Builder

	doc.WriteString(preamble)
	renderPlatformActions(&doc, authz.Rules())
	renderEngagementActions(&doc, authz.Rules())
	renderGuards(&doc, authz.Rules())
	doc.WriteString(postamble)

	return []byte(doc.String())
}

const preamble = `<!-- Generated by internal/authz/authzdoc from the rule table in internal/authz.
     Do not edit: run ` + "`make generate`" + `. CI fails if this file and the table disagree. -->

# Authorization

Blacklight has exactly one place that decides what somebody may do:
` + "`authz.Can(ctx, subject, action, resource)`" + `, in ` + "`internal/authz`" + `. No handler makes a role
decision — handlers are not given the information to make one. This page is that package's rule
table, rendered.

v1 decided per handler, and every authorization failure in it followed from that: an ungated user
management page, spectators who could write, and two definitions of "blue" that disagreed. The
tables below are the model in full; if a permission is not in them, nobody has it.

## The two levels

| Level | Values | Means |
|---|---|---|
| Platform role | ` + "`admin`, `member`" + ` | What you may do to this installation. Every account has exactly one. |
| Engagement role | ` + "`lead`, `red`, `blue`, `observer`" + ` | What you may do inside one engagement. One per engagement you belong to; none if you are not a member. |

They are separate vocabularies on purpose. Being a lead of an engagement confers nothing on the
installation, and being a platform admin is not a seat in anybody's exercise — although an admin
does hold every engagement-scoped action on every engagement, membership or not.

## How to read the tables

- ` + "`✓`" + ` — holds the action. ` + "`·`" + ` — does not.
- **Denial is the default.** A combination that is not a ` + "`✓`" + ` is refused, and refusal says why.
- A refusal that would confirm something the caller may not know — that an engagement exists, that
  an unrevealed step exists — is answered **404**, not 403. The rest are 403.
- The **token scope** column applies only to requests authenticated by a service token. A token
  must hold both the listed scope *and* its owner's live role: revoking or demoting the owner
  constrains the token immediately, with no change to the token.

`

const postamble = `## Service tokens

A service token is fenced twice. The action must be permitted to the token's **owner**, by the
tables above and their live role at the moment of the request, **and** the token must carry the
scope listed for that action. Neither fence is sufficient on its own, so a token issued while its
holder was an administrator stops being an administrator's token the moment they are demoted.

Scopes are deliberately coarse; the full list is derived from the tables above.

## Where this is enforced

In one middleware, ` + "`internal/httpapi/authorize.go`" + `, which is the only caller of ` + "`authz.Can`" + ` in the
tree — a test fails the build if a second one appears. Each operation in ` + "`api/openapi.yaml`" + ` names the
action it needs (` + "`x-authz-action`" + `), or carries a written exemption; an operation that names neither
is a server that refuses to start. See [` + "`docs/api.md`" + `](api.md#authorization) for the mapping and
[` + "`docs/http.md`" + `](http.md#authorization) for what a refusal looks like on the wire.

## Changing this model

Edit the rule table in ` + "`internal/authz/policy.go`" + ` and run ` + "`make generate`" + `. Everything else follows:

- Adding an ` + "`Action`" + ` without a rule fails the exhaustiveness test — silence is not a permission.
- The permission matrix in ` + "`internal/authz`" + `'s tests enumerates from the same table, so a new action
  arrives with its whole row asserted.
- Role names exist only in ` + "`internal/authz`" + `. A role string anywhere else in the Go tree fails a test,
  which is the direct fix for v1's two contradictory definitions of "blue".
`

// renderPlatformActions renders the actions that act on the installation.
func renderPlatformActions(doc *strings.Builder, rules []authz.Rule) {
	doc.WriteString("## Platform actions\n\n")
	doc.WriteString("Acts on the installation itself. Engagement membership is irrelevant to these.\n\n")

	doc.WriteString("| Action |")
	for _, role := range authz.PlatformRoles() {
		fmt.Fprintf(doc, " %s |", role)
	}
	doc.WriteString(" Token scope | What it covers |\n")
	doc.WriteString("|---|")
	for range authz.PlatformRoles() {
		doc.WriteString(":-:|")
	}
	doc.WriteString("---|---|\n")

	for _, rule := range rules {
		if rule.Resource.EngagementScoped() {
			continue
		}
		fmt.Fprintf(doc, "| `%s` |", rule.Name)
		for _, role := range authz.PlatformRoles() {
			fmt.Fprintf(doc, " %s |", cell(holdsPlatform(rule, role)))
		}
		fmt.Fprintf(doc, " `%s` | %s |\n", rule.Token, rule.Summary)
	}
	doc.WriteString("\n")
}

// renderEngagementActions renders the actions that act inside one engagement.
func renderEngagementActions(doc *strings.Builder, rules []authz.Rule) {
	doc.WriteString("## Engagement actions\n\n")
	doc.WriteString("Acts on one engagement's contents. The engagement-role columns mean *in that engagement*;\n" +
		"a role held elsewhere grants nothing here. A non-member is refused with a 404.\n\n")

	doc.WriteString("| Action | platform admin |")
	for _, role := range authz.EngagementRoles() {
		fmt.Fprintf(doc, " %s |", role)
	}
	doc.WriteString(" non-member | Token scope | What it covers |\n")
	doc.WriteString("|---|:-:|")
	for range authz.EngagementRoles() {
		doc.WriteString(":-:|")
	}
	doc.WriteString(":-:|---|---|\n")

	for _, rule := range rules {
		if !rule.Resource.EngagementScoped() {
			continue
		}
		fmt.Fprintf(doc, "| `%s` | %s |", rule.Name, cell(holdsPlatform(rule, authz.PlatformRoleAdmin)))
		for _, role := range authz.EngagementRoles() {
			fmt.Fprintf(doc, " %s |", cell(holdsEngagement(rule, role)))
		}
		fmt.Fprintf(doc, " %s | `%s` | %s |\n", cell(false), rule.Token, rule.Summary)
	}
	doc.WriteString("\n")
}

// renderGuards lists the conditions that apply on top of a role, and the
// actions carrying each. A guard is the only way a ✓ above is conditional, so
// it has to be as visible as the tables are.
func renderGuards(doc *strings.Builder, rules []authz.Rule) {
	byGuard := map[authz.Guard][]string{}
	order := []authz.Guard{}
	for _, rule := range rules {
		if rule.Guard == authz.GuardNone {
			continue
		}
		if _, seen := byGuard[rule.Guard]; !seen {
			order = append(order, rule.Guard)
		}
		byGuard[rule.Guard] = append(byGuard[rule.Guard], "`"+rule.Name+"`")
	}
	if len(order) == 0 {
		return
	}

	doc.WriteString("## Guards\n\n")
	doc.WriteString("A guard is an extra condition applied *after* a role grants the action, so a ✓ above can\n" +
		"still be refused for one of these reasons.\n\n")
	for _, guard := range order {
		fmt.Fprintf(doc, "- **`%s`** — %s\n  Applies to: %s.\n",
			guard, describe(guard), strings.Join(byGuard[guard], ", "))
	}
	doc.WriteString("\n")
}

// guardDescriptions is the prose for each guard. It lives here rather than on
// the rule because it describes the condition, which several rules share.
// A guard with no description renders as one, loudly, rather than as a blank.
var guardDescriptions = map[authz.Guard]string{
	authz.GuardBlindMode: "In a blind engagement, a member in the `blue` seat cannot reach a step that has not " +
		"been revealed — not even to learn it exists. The same filter is applied in the query layer, so a " +
		"missing rule still cannot leak one. A platform admin who is *not* a member of the engagement is " +
		"unaffected; one who has taken the blue seat is held to it.",
}

// describe returns a guard's prose, or a placeholder that reads as the omission
// it is. A blank would render a bullet that says nothing and looks finished;
// TestEveryGuardIsDescribed fails on it either way.
func describe(guard authz.Guard) string {
	if description, ok := guardDescriptions[guard]; ok {
		return description
	}
	return "**UNDOCUMENTED.** Add a description to guardDescriptions in internal/authz/authzdoc."
}

// holdsPlatform reports whether a platform role holds a rule outright.
func holdsPlatform(rule authz.Rule, role authz.PlatformRole) bool {
	for _, allowed := range rule.Platform {
		if allowed == role {
			return true
		}
	}
	return false
}

// holdsEngagement reports whether an engagement role holds a rule within its
// own engagement.
func holdsEngagement(rule authz.Rule, role authz.EngagementRole) bool {
	for _, allowed := range rule.Engagement {
		if allowed == role {
			return true
		}
	}
	return false
}

func cell(yes bool) string {
	if yes {
		return held
	}
	return notHeld
}
